from pathlib import Path
from html import escape
from os import environ
from hashlib import sha256
import re
import shutil
from format_visuals import card as format_card, detail as format_detail
from content import COPY, RANKING_UI, EXTRA, RULES, PENALTIES, FORMATS, PRIVACY
R=Path(__file__).parent/'dist'
BASE=environ.get('ATX_BASE_PATH','/atxracing/').rstrip('/')+'/'
SITE_URL=environ.get('ATX_SITE_URL','https://athoxmotorsport-lab.github.io'+BASE).rstrip('/')+'/'
for image in ('site-background.jpg','site-background.webp','landing-banner.jpg','driver-levels-cutout.png','driver-levels-cutout.webp'):
 shutil.copy2(Path(__file__).parent/'media'/image,R/'assets'/image)
(R/'assets'/'gt3').mkdir(parents=True,exist_ok=True)
for photo in (Path(__file__).parent/'media'/'gt3').glob('*.webp'):
 shutil.copy2(photo,R/'assets'/'gt3'/photo.name)
(R/'assets'/'gt3'/'thumbs').mkdir(parents=True,exist_ok=True)
for photo in (Path(__file__).parent/'media'/'gt3'/'thumbs').glob('*.webp'):
 shutil.copy2(photo,R/'assets'/'gt3'/'thumbs'/photo.name)
for folder in ('circuits','events','fonts'):
 (R/'assets'/folder).mkdir(parents=True,exist_ok=True)
 for photo in (Path(__file__).parent/'media'/folder).iterdir():
  if photo.is_file():shutil.copy2(photo,R/'assets'/folder/photo.name)
CSS=(Path(__file__).parent/'src/fonts.css').read_text()+'\n'+(Path(__file__).parent/'src/site.css').read_text()
CSS=re.sub(r'/\*.*?\*/','',CSS,flags=re.S)
CSS=re.sub(r'\s+',' ',CSS)
CSS=re.sub(r'\s*([{}:;,>])\s*',r'\1',CSS).strip()
(R/'assets/site.min.css').write_text(CSS)
(R/'assets/site.min.js').write_text((Path(__file__).parent/'src/site.js').read_text())
(R/'assets/ranking.min.js').write_text((Path(__file__).parent/'src/ranking.js').read_text())
(R/'assets/circuit-images.min.js').write_text((Path(__file__).parent/'src/circuit-images.js').read_text())
(R/'assets/profile-media.min.js').write_text((Path(__file__).parent/'src/profile-media.js').read_text())
(R/'assets/account.min.js').write_text((Path(__file__).parent/'src/account.js').read_text())
(R/'assets/insignia.min.js').write_text((Path(__file__).parent/'src/insignia.js').read_text())
(R/'assets/entry.min.js').write_text((Path(__file__).parent/'src/entry.js').read_text())
(R/'assets/gate.min.js').write_text((Path(__file__).parent/'src/gate.js').read_text())
(R/'assets/public-data.min.js').write_text((Path(__file__).parent/'src/public-data.js').read_text())
(R/'assets/community.min.js').write_text((Path(__file__).parent/'src/community.js').read_text())
(R/'assets/messages.min.js').write_text((Path(__file__).parent/'src/messages.js').read_text())
(R/'assets/events.min.js').write_text((Path(__file__).parent/'src/events.js').read_text())
(R/'assets/admin.min.js').write_text((Path(__file__).parent/'src/admin.js').read_text())
(R/'assets/registration.min.js').write_text((Path(__file__).parent/'src/registration.js').read_text())
(R/'assets/media.min.js').write_text((Path(__file__).parent/'src/media.js').read_text())
def write(path,html):
 path.parent.mkdir(parents=True,exist_ok=True)
 html=re.sub(r'(href|src)="/assets/([^"?]+\.(?:js|css))"',lambda m:f'{m[1]}="/assets/{m[2]}?v={sha256((R/"assets"/m[2]).read_bytes()).hexdigest()[:12]}"',html)
 path.write_text(html.replace('href="/','href="'+BASE).replace('src="/','src="'+BASE))
T={
'fr':dict(select='Choisissez votre ligue',acc='Compétitions GT3 sur Assetto Corsa Competizione',ace='La nouvelle scène Assetto Corsa EVO',enter='Découvrir la ligue',courses='Courses',ranking='Classements',records='Meilleurs temps',profile='Profil pilote',pilots='Pilotes',welcome='Deux jeux. Une communauté.',choose='Choisir une ligue',acc_intro='Retrouvez les courses programmées, les résultats et les pilotes de la ligue ACC.',ace_intro='L’espace ACE se prépare. Les courses et classements apparaîtront dès que les données ACE seront publiées.',events_desc='Les prochaines courses de la ligue.',ranking_desc='Points et performances des pilotes, par catégorie.',records_desc='Les meilleurs tours valides, classés par circuit et par voiture.',profile_desc='Votre espace pilote, vos statistiques et vos résultats.',pilots_desc='Recherchez un pilote ou une équipe et consultez sa carte publique.',soon='Les données ACE seront affichées après la mise en place du collecteur et de la base de données dédiés.',back='Toutes les ligues',category='Catégorie',circuit='Circuit',legacy='Site ACC actuel'),
'en':dict(select='Choose your league',acc='GT3 racing on Assetto Corsa Competizione',ace='The new Assetto Corsa EVO racing scene',enter='Explore the league',courses='Races',ranking='Standings',records='Best laps',profile='Driver profile',pilots='Drivers',welcome='Two games. One community.',choose='Choose a league',acc_intro='Explore scheduled races, results and drivers in the ACC league.',ace_intro='The ACE space is being prepared. Races and standings will appear when ACE data is published.',events_desc='Upcoming league races.',ranking_desc='Driver points and performance by category.',records_desc='Fastest valid laps by track and car.',profile_desc='Your driver space, statistics and results.',pilots_desc='Search for a driver or team and view their public card.',soon='ACE data will appear after the dedicated collector and database are ready.',back='All leagues',category='Category',circuit='Track',legacy='Current ACC site'),
'de':dict(select='Wähle deine Liga',acc='GT3-Rennen in Assetto Corsa Competizione',ace='Die neue Rennszene für Assetto Corsa EVO',enter='Liga entdecken',courses='Rennen',ranking='Wertungen',records='Bestzeiten',profile='Fahrerprofil',welcome='Zwei Spiele. Eine Community.',choose='Liga wählen',acc_intro='Entdecke geplante Rennen, Ergebnisse und Fahrer der ACC-Liga.',ace_intro='Der ACE-Bereich wird vorbereitet. Rennen und Wertungen erscheinen, sobald ACE-Daten vorliegen.',events_desc='Die nächsten Rennen der Liga.',ranking_desc='Fahrerpunkte und Leistung nach Kategorie.',records_desc='Schnellste gültige Runden nach Strecke und Fahrzeug.',profile_desc='Öffentliche Fahrerprofile mit Statistiken und Ergebnissen.',soon='ACE-Daten erscheinen, sobald Collector und Datenbank eingerichtet sind.',back='Alle Ligen',category='Kategorie',circuit='Strecke',legacy='Bisherige ACC-Seite'),
'it':dict(select='Scegli la tua lega',acc='Gare GT3 su Assetto Corsa Competizione',ace='La nuova scena di Assetto Corsa EVO',enter='Scopri la lega',courses='Gare',ranking='Classifiche',records='Giri migliori',profile='Profilo pilota',welcome='Due giochi. Una comunità.',choose='Scegli una lega',acc_intro='Scopri le gare in programma, i risultati e i piloti della lega ACC.',ace_intro='Lo spazio ACE è in preparazione. Gare e classifiche appariranno quando i dati ACE saranno pubblicati.',events_desc='Le prossime gare della lega.',ranking_desc='Punti e prestazioni dei piloti per categoria.',records_desc='I migliori giri validi per circuito e auto.',profile_desc='Profili pubblici dei piloti con statistiche e risultati.',soon='I dati ACE appariranno quando collector e database dedicati saranno pronti.',back='Tutte le leghe',category='Categoria',circuit='Circuito',legacy='Sito ACC attuale'),
'es':dict(select='Elige tu liga',acc='Carreras GT3 en Assetto Corsa Competizione',ace='La nueva escena de Assetto Corsa EVO',enter='Explorar la liga',courses='Carreras',ranking='Clasificaciones',records='Mejores vueltas',profile='Perfil de piloto',welcome='Dos juegos. Una comunidad.',choose='Elegir liga',acc_intro='Consulta las próximas carreras, los resultados y los pilotos de la liga ACC.',ace_intro='El espacio ACE está en preparación. Las carreras y clasificaciones aparecerán cuando se publiquen datos de ACE.',events_desc='Las próximas carreras de la liga.',ranking_desc='Puntos y rendimiento de pilotos por categoría.',records_desc='Las vueltas válidas más rápidas por circuito y coche.',profile_desc='Perfiles públicos de pilotos con estadísticas y resultados.',soon='Los datos de ACE aparecerán cuando el collector y la base de datos estén listos.',back='Todas las ligas',category='Categoría',circuit='Circuito',legacy='Sitio ACC actual')}
T={lang:T[lang] for lang in ('fr','en')}
language_names={'fr':'Français','en':'English'}

DOCK_ICONS={
 'home':'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',
 'courses':'<path d="M5 21V4m0 1c5-3 9 3 14 0v10c-5 3-9-3-14 0"/>',
 'calendar':'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18m-13 4h3m2 0h3m-8 4h3"/>',
 'ranking':'<path d="M4 21h16M6 21v-7h4v7m0 0V9h4v12m0 0v-5h4v5M8 4l1 2 2 .3-1.5 1.5.4 2.2L8 9l-1.9 1 .4-2.2L5 6.3 7 6z"/>',
 'records':'<circle cx="12" cy="13" r="8"/><path d="M12 13l3-3m-3-9v4m-3-4h6M18 5l2 2"/>',
 'archives':'<rect x="3" y="4" width="18" height="5" rx="1"/><path d="M5 9v11h14V9m-9 5h4"/>',
 'rules':'<path d="M7 3h8l4 4v14H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zM15 3v5h5M9 13h6m-6 4h6"/>',
 'profile':'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
 'circuits':'<path d="M5 19c4-1 2-7 7-8s3-6 7-6M4 4l3 3-3 3m13 4 3 3-3 3"/>',
 'live':'<rect x="3" y="6" width="18" height="13" rx="2"/><path d="m10 10 5 3-5 3zM8 3h8"/>',
 'about':'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>'
}

def dock(lang,game,section,t):
 labels={'fr':{'courses':'Compétitions','ranking':'Classements','circuits':'Circuits','live':'Live & Replay','rules':'Règlement','profile':'Profil pilote','about':'ATXRACING'},'en':{'courses':'Competitions','ranking':'Standings','circuits':'Circuits','live':'Live & Replay','rules':'Rules','profile':'Driver profile','about':'ATXRACING'}}[lang]
 items=[(s,labels[s],f'/{lang}/{game or "acc"}/{s}.html') for s in ('courses','ranking','circuits','live','rules','profile')]+[('about',labels['about'],f'/{lang}/about.html')]
 links=[]
 for name,label,url in items:
  icon=f'<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{DOCK_ICONS[name]}</svg>'
  current=' aria-current="page"' if section==name else ''
  links.append(f'<a href="{url}" aria-label="{escape(label)}" title="{escape(label)}"{current}>{icon}<span>{escape(label)}</span></a>')
 return '<nav class="side-dock" aria-label="Navigation">'+''.join(links)+'</nav>'
def selector(game):
 out=f'<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url={BASE}fr/{game}/"><title>{game.upper()} · ATXRACING</title><link rel="canonical" href="/fr/{game}/"></head><body><main><p><a href="/fr/{game}/">{game.upper()} →</a></p></main></body></html>'
 write(R/game/'index.html',out)
def page(lang,game,section):
 t={**T[lang], **EXTRA[lang], **{key:value[0] for key,value in FORMATS[lang].items()},'privacy':PRIVACY[lang]['title']}; v={**COPY[lang], **RANKING_UI[lang], **EXTRA[lang], **{key+'_lead':value[1] for key,value in FORMATS[lang].items()},'privacy_lead':PRIVACY[lang]['lead']}; t['course']=t['courses'];v['course_lead']=v['courses_lead'];v['pilots_lead']=t['pilots_desc'];t['about']='À propos' if lang=='fr' else 'About';t['circuits']='Circuits';v['circuits_lead']='Découvrez les circuits ACC et leurs meilleurs tours validés.' if lang=='fr' else 'Explore ACC circuits and their validated best laps.';t['live']='Live & Replay';v['live_lead']='Suivez les prochaines diffusions ATXRACING et retrouvez les replays liés aux épreuves.' if lang=='fr' else 'Watch upcoming ATXRACING broadcasts and find event replays.';t['admin']='Administration ATX Racing' if lang=='fr' else 'ATX Racing administration';v['admin_lead']='Gérez vos courses, le calendrier et les diffusions.' if lang=='fr' else 'Manage your races, calendar and broadcasts.';t['messages']='Messages privés' if lang=='fr' else 'Private messages';v['messages_lead']='Échangez directement avec les autres pilotes connectés à Steam.' if lang=='fr' else 'Talk directly with other Steam-connected drivers.';title=t.get(section,t['choose']); root='/' if not game else f'/{lang}/{game}/'
 root=f'/{lang}/{game or "acc"}/'
 nav=dock(lang,game,section,t)
 switch=f'<nav class="game-switch" aria-label="Jeu / Game"><a href="/{lang}/acc/" '+('aria-current="true"' if game=='acc' else '')+f'>ACC</a><a href="/{lang}/ace/" '+('aria-current="true"' if game=='ace' else '')+'>ACE</a></nav>'
 languages='<nav class="header-languages" aria-label="Langue / Language">'+''.join(f'<a href="/{l}/{game+"/" if game else ""}{"" if section in ("league","home") else section+".html"}" hreflang="{l}" '+('aria-current="page"' if l==lang else '')+f' lang="{l}" aria-label="{escape(language_names[l])}" title="{escape(language_names[l])}"><img src="/assets/flag-{l}.svg" alt=""></a>' for l in T)+'</nav>'
 steam=f'<a class="steam-connect" data-steam-link href="/{lang}/{game or "acc"}/profile.html" aria-label="Steam"><span class="steam-mark" aria-hidden="true">●</span><span data-steam-label>{"Connexion Steam" if lang=="fr" else "Sign in with Steam"}</span></a>'
 coin_label='Coins ATX' if lang=='fr' else 'ATX Coins'
 coins=f'<a class="header-coins" href="/{lang}/{game or "acc"}/profile.html#coins" aria-label="{coin_label}"><span aria-hidden="true">◆</span><strong data-atx-coins>—</strong><small>ATX</small></a>'
 relative=f'{lang}/{game+"/" if game else ""}{"" if section in ("league","home") else section+".html"}'
 canonical=SITE_URL+relative
 about_description={'fr':'Découvrez ATX Motorsport, son équipe de pilotes, et ATX Racing, organisateur de courses et championnats de sim racing.','en':'Discover ATX Motorsport, its driver team, and ATX Racing, organiser of sim racing events and championships.'}
 description=escape(about_description[lang] if section=='about' else v.get(section+'_lead',v.get('lead_'+game,'ATXRACING, communauté de sim racing ACC et ACE.')))
 head=f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050505"><meta name="atx-base" content="{BASE}"><meta name="description" content="{description}"><link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:site_name" content="ATXRACING"><meta property="og:title" content="{escape(title)} · ATXRACING"><meta property="og:description" content="{description}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{SITE_URL}assets/banner.webp"><meta name="twitter:card" content="summary_large_image"><title>{escape(title)} · ATXRACING</title><link rel="preload" href="/assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="preconnect" href="https://twjpjzalyvbsdpbzhqln.supabase.co" crossorigin><link rel="stylesheet" href="/assets/site.min.css"></head><body class="site-locked" data-game="{game}" data-page="{section}"><header class="topbar"><div class="wrap top-inner"><a class="brand" href="/" aria-label="ATXRACING"><img src="/assets/logo.webp" alt="ATXRACING"></a>{switch}<div class="header-tools">{languages}{coins}{steam}</div></div></header>{nav}'
 footer_links=''.join(f'<a href="/{lang}/{game or "acc"}/{slug}.html">{escape(label)}</a>' for slug,label in [('courses','Compétitions' if lang=='fr' else 'Competitions'),('ranking','Classements' if lang=='fr' else 'Standings'),('circuits','Circuits'),('live','Live & Replay'),('rules','Règlement' if lang=='fr' else 'Rules'),('profile','Profil pilote' if lang=='fr' else 'Driver profile')])
 footer=f'<footer class="footer"><div class="wrap footer-grid"><div><strong>ATXRACING</strong><p>{"Une communauté, deux univers de course." if lang=="fr" else "One community, two racing worlds."}</p><a href="mailto:athoxmotorsport@gmail.com">athoxmotorsport@gmail.com</a></div><nav class="footer-sitemap" aria-label="Plan du site">{footer_links}<a href="/{lang}/about.html">ATXRACING</a><a href="/{lang}/{game or "acc"}/privacy.html">{escape(t["privacy"])}</a></nav><nav class="footer-socials" aria-label="Réseaux sociaux"><a href="https://discord.com/invite/dgyJJYTSsD">Discord</a><a href="https://www.twitch.tv/atxracing">Twitch</a><a href="https://www.thesimgrid.com/communities/atxracing">SimGrid</a></nav>{languages.replace("header-languages","footer-languages")}</div><div class="wrap footer-legal">© 2026 ATXRACING</div></footer>'
 if section=='home':
  home_copy={
   'fr':('ESPACE PILOTE','MON','PADDOCK.','Bienvenue','Choisissez votre univers de course. Votre profil et votre identité Steam vous suivent dans les deux jeux.','Créer ou compléter mon profil','COMPÉTITION','Entrer dans la ligue ACC','EN PRÉPARATION','Découvrir ACE'),
   'en':('DRIVER SPACE','MY','PADDOCK.','Welcome','Choose your racing world. Your profile and Steam identity stay with you across both games.','Create or complete my profile','COMPETITION','Enter the ACC league','COMING SOON','Explore ACE')
  }[lang]
  eyebrow,first,last,welcome,lead,profile_action,acc_state,acc_action,ace_state,ace_action=home_copy
  guest_name='pilote' if lang=='fr' else 'driver'
  body=f'''<main class="wrap content paddock-home"><section class="paddock-intro"><a class="eyebrow" href="/{lang}/about.html">ATXRACING / {eyebrow} ↗</a><h1>{first} <em>{last}</em></h1><p class="paddock-welcome">{welcome}, <strong data-driver-name>{guest_name}</strong>.</p><p class="paddock-lead">{lead}</p><a class="paddock-profile-link" href="/{lang}/acc/profile.html">{profile_action} <span aria-hidden="true">↗</span></a></section><section class="paddock-games" aria-label="ACC / ACE"><a class="paddock-game" href="/{lang}/acc/"><img src="/assets/acc-banner.webp" alt="" width="683" height="683" fetchpriority="high"><span class="paddock-game-copy"><span class="paddock-game-state">{acc_state}</span><strong>ACC</strong><span class="paddock-game-action">{acc_action} <span aria-hidden="true">↗</span></span></span></a><a class="paddock-game" href="/{lang}/ace/"><img src="/assets/ace-banner.webp" alt="" width="683" height="683"><span class="paddock-game-copy"><span class="paddock-game-state">{ace_state}</span><strong>ACE</strong><span class="paddock-game-action">{ace_action} <span aria-hidden="true">↗</span></span></span></a></section></main>'''
 elif section=='about':
  about={
   'fr':dict(kicker='UN PROJET · DEUX BRANCHES · UNE MÊME PASSION',title='LA PASSION NOUS RASSEMBLE. LA PISTE NOUS FAIT GRANDIR.',intro='ATX est né d’une volonté simple : poursuivre une aventure collective autour du sport automobile virtuel, avec engagement, ambition et esprit d’équipe.',motorsport='ATX Motorsport',motorsport_tag='L’ÉQUIPE',motorsport_body='Après avoir quitté l’équipe française dont je faisais partie en tant que pilote, j’ai décidé de créer un nouveau projet correspondant davantage à mes ambitions et à ma vision. Accompagné de deux anciens membres partageant la même motivation, j’ai fondé ATX Motorsport afin de construire une structure dynamique, durable et tournée vers l’avenir.',motorsport_goal='Notre objectif est de réunir des pilotes passionnés, de favoriser leur progression et de participer à différentes compétitions dans un environnement sérieux, convivial et respectueux. Le recrutement et le développement de l’équipe occupent une place essentielle dans cette démarche.',racing='ATX Racing',racing_tag='L’ORGANISATION',racing_body='ATX Racing représente le volet organisationnel du projet. Cette initiative est née de l’envie de proposer nos propres événements, avec des formats correspondant davantage à notre vision de la compétition.',racing_goal='Courses ponctuelles, championnats structurés et rendez-vous accessibles : nous voulons proposer des compétitions intéressantes où la communauté peut se retrouver et s’affronter.',future='Notre vision',future_title='UNE COURSE TOUJOURS À PORTÉE DE VOLANT.',future_body='À plus long terme, nous souhaitons mettre en place des serveurs supplémentaires pour proposer des courses régulières tout au long de la journée — toutes les heures ou toutes les deux heures — autour d’un format d’environ 45 minutes.',future_detail='Ces courses pourront rejoindre un championnat permanent, avec inscription et suivi directement depuis le site. Le projet est encore en développement, mais son ambition est claire : offrir une expérience régulière, organisée et stimulante.',together='Deux branches complémentaires',together_body='ATX Motorsport rassemble les pilotes et porte les couleurs de l’équipe en compétition. ATX Racing imagine et organise les événements lors desquels la communauté peut se retrouver et s’affronter.',values=['PASSION','ENGAGEMENT','PROGRESSION','PARTAGE'],cta='REJOIGNEZ L’AVENTURE',cta_body='Nous continuons à recruter de nouveaux talents pour faire grandir l’équipe et développer des compétitions de qualité.',cta_link='Devenir pilote ATX'),
   'en':dict(kicker='ONE PROJECT · TWO BRANCHES · ONE PASSION',title='PASSION BRINGS US TOGETHER. RACING MAKES US GROW.',intro='ATX was born from a simple desire: to continue a collective adventure around virtual motorsport, driven by commitment, ambition and team spirit.',motorsport='ATX Motorsport',motorsport_tag='THE TEAM',motorsport_body='After leaving the French team I raced for, I decided to create a project more closely aligned with my ambitions and vision. Together with two former members who shared that motivation, I founded ATX Motorsport to build a dynamic, sustainable organisation focused on the future.',motorsport_goal='Our goal is to bring passionate drivers together, help them progress and compete in a serious, welcoming and respectful environment. Recruitment and team development are central to that approach.',racing='ATX Racing',racing_tag='THE ORGANISATION',racing_body='ATX Racing is the organisational branch of the project. It grew from our desire to create our own events, with formats that better reflect our vision of competition.',racing_goal='Standalone races, structured championships and accessible events: we want to create engaging competitions where the community can meet and race.',future='Our vision',future_title='A RACE ALWAYS WITHIN REACH.',future_body='In the longer term, we plan to add servers offering regular races throughout the day — every hour or every two hours — around a 45-minute format.',future_detail='Those races could form a permanent championship, with registration and tracking directly through this website. The project is still developing, but its ambition is clear: a regular, organised and rewarding racing experience.',together='Two complementary branches',together_body='ATX Motorsport brings drivers together and carries the team colours in competition. ATX Racing creates and organises the events where the community meets and competes.',values=['PASSION','COMMITMENT','PROGRESS','SHARING'],cta='JOIN THE ADVENTURE',cta_body='We continue to recruit new talent to grow the team and develop high-quality competitions.',cta_link='Become an ATX driver')
  }[lang]
  values=''.join(f'<li>{escape(value)}</li>' for value in about['values'])
  body=f'''<main class="wrap content about-content"><section class="about-hero"><span class="eyebrow">{escape(about['kicker'])}</span><h1>{escape(about['title'])}</h1><p>{escape(about['intro'])}</p></section><section class="about-branches"><article><span class="meta">01 / {escape(about['motorsport_tag'])}</span><h2>{escape(about['motorsport'])}</h2><p>{escape(about['motorsport_body'])}</p><p>{escape(about['motorsport_goal'])}</p></article><article><span class="meta">02 / {escape(about['racing_tag'])}</span><h2>{escape(about['racing'])}</h2><p>{escape(about['racing_body'])}</p><p>{escape(about['racing_goal'])}</p></article></section><section class="about-future"><div><span class="eyebrow">03 / {escape(about['future'])}</span><h2>{escape(about['future_title'])}</h2></div><div><p>{escape(about['future_body'])}</p><p>{escape(about['future_detail'])}</p></div></section><section class="about-union"><span class="eyebrow">ATX / MOTORSPORT + RACING</span><h2>{escape(about['together'])}</h2><p>{escape(about['together_body'])}</p><ul>{values}</ul></section><section class="about-recruit"><div><span class="eyebrow">DISCORD / RECRUTEMENT</span><h2>{escape(about['cta'])}</h2><p>{escape(about['cta_body'])}</p></div><a class="action" href="https://discord.gg/Vk4SD4nhbj" target="_blank" rel="noopener noreferrer">{escape(about['cta_link'])} <span aria-hidden="true">↗</span></a></section></main>'''
 else:
  main='<main class="wrap content">'
  if section=='league':
   main+=f'<section class="league-overview"><div class="overview-copy"><span class="eyebrow">{escape(v["stage"])} / {game.upper()}</span><h1>{escape(v["league_"+game])}</h1><p>{escape(v["lead_"+game])}</p><a class="action" href="/{lang}/{game}/courses.html">{escape(v["discover"])} <span aria-hidden="true">↗</span></a></div><div class="overview-art"><img src="/assets/{game}-banner.webp" alt=""></div></section><div class="section-intro"><span class="eyebrow">{game.upper()} / 01—04</span><h2>{escape(v["section"])}</h2></div><div class="grid feature-grid">'+''.join(f'<a class="panel feature-panel" href="/{lang}/{game}/{s}.html"><span class="meta">0{i} / {game.upper()}</span><h3>{escape(t[s])} <span aria-hidden="true">↗</span></h3><p>{escape(v["courses_lead" if s=="courses" else s+"_lead"])}</p></a>' for i,s in enumerate(['courses','ranking','records','profile'],1))+'</div>'
  else:
   main+=f'<section class="page-masthead"><div class="masthead-copy"><span class="eyebrow">{game.upper()} / {escape(v["stage"])}</span><h1>{escape(t[section])}</h1><p>{escape(v[section+"_lead"])}</p></div><div class="masthead-art"><img src="/assets/{game}-banner.webp" alt=""></div></section>'
   if section=='admin':
    main+='<section id="admin-app" class="admin-app" aria-live="polite"></section>'
   if section=='profile':
    intro='Votre identité. Votre rythme. Votre prochaine course.' if lang=='fr' else 'Your identity. Your pace. Your next race.'
    level_wait='Niveau en attente de résultats' if lang=='fr' else 'Level awaiting results'
    level_label='Progression du pilote' if lang=='fr' else 'Driver progression'
    engineer=('Votre ingénieur de course a retrouvé votre identité Steam. Vérifiez les informations connues puis complétez les éléments manquants.' if lang=='fr' else 'Your race engineer found your Steam identity. Review the known information, then complete anything missing.')
    main+=f'<aside class="race-engineer" data-profile-engineer hidden><span class="race-engineer-mark" aria-hidden="true">IE</span><div><strong>{"INGÉNIEUR DE COURSE" if lang=="fr" else "RACE ENGINEER"}</strong><p>{engineer}</p></div></aside><figure class="driver-levels" data-driver-levels><div class="driver-levels-art"><img class="driver-levels-base" src="/assets/driver-levels-cutout.webp" alt="" width="1774" height="887"><div class="driver-levels-reveal" aria-hidden="true"><img src="/assets/driver-levels-cutout.webp" alt="" width="1774" height="887"></div></div><figcaption><div class="driver-levels-caption"><span data-level-status>{level_wait}</span><span class="driver-levels-current" data-level-current>—</span></div><span class="driver-levels-track" role="progressbar" aria-label="{level_label}" aria-valuemin="0" aria-valuemax="5" aria-valuenow="0" aria-valuetext="{level_wait}"><span class="driver-levels-fill"></span></span><span class="driver-levels-steps" aria-hidden="true"><span>ROOKIE</span><span>CHALLENGER</span><span>PRO</span><span>ELITE</span><span>ALIEN</span></span></figcaption></figure><section id="account-app" class="account-app" aria-live="polite"><p>{intro}</p></section><noscript><p>{"Activez JavaScript pour vous connecter et modifier votre profil." if lang=="fr" else "Enable JavaScript to sign in and edit your profile."}</p></noscript>'
   if section=='privacy':main+='<div class="privacy-sections">'+''.join(f'<article><span class="meta">{str(i).zfill(2)}</span><h2>{escape(heading)}</h2><p>{escape(copy)}</p></article>' for i,(heading,copy) in enumerate(PRIVACY[lang]['parts'],1))+'</div><p><a class="pill" href="mailto:athoxmotorsport@gmail.com">athoxmotorsport@gmail.com</a></p>'
   elif game=='ace' and section not in ('profile','messages'): main+=f'<section class="status-panel"><span class="eyebrow">ACE / {escape(v["published"])}</span><h2>{escape(v["league_ace"])}</h2><p>{escape(v["ace_pending"])}</p><a class="pill" href="/{lang}/acc/">{escape(v["back_acc"])} ↗</a></section>'
   else:
    if section=='courses':
     main+=f'<div class="section-intro"><span class="eyebrow">01 / {escape(v["formats"])}</span><h2>{escape(v["formats"])}</h2></div><div class="format-grid">'+''.join(format_card(lang,key,name,i) for i,(key,(name,description)) in enumerate(zip(("worldgt-sprint","worldgt-endurance","daily-race","atx-series"),v["formats_items"]),1))+'</div>'
     main+=f'<div class="section-intro"><span class="eyebrow">02 / {escape(v["schedule"])}</span><h2>{escape(v["next"])}</h2></div>'
    if section=='ranking':
     main+=f'<div class="section-intro"><span class="eyebrow">01 / {escape(v["source"])}</span><h2 data-ranking-title>{"Classement par pilote" if lang=="fr" else "Driver standings"}</h2></div>'
     main+='<div id="ranking-app" aria-live="polite"><nav class="ranking-views" aria-label="'+escape(v['standings'])+'">'+''.join(f'<button type="button" data-view="{key}">{escape(label)}</button>' for key,label in [('points','Classement par pilote' if lang=='fr' else 'Driver standings'),('team','Classement par équipe' if lang=='fr' else 'Team standings')])+'</nav><div id="ranking-content"><p class="loading">…</p></div></div>'
    if section in ('records','circuits'): main+=f'<div class="section-intro"><span class="eyebrow">01 / {escape(v["source"])}</span><h2>{escape(v["fastest"])}</h2></div><div id="circuit-grid" class="record-circuits" aria-label="{escape(v["track"])}"></div><div id="record-spotlight" class="record-spotlight" aria-live="polite"></div>'
    if section=='circuits':main+='<div id="results" aria-live="polite"></div>'
    if section=='live':main+=f'<section class="live-stage"><span class="eyebrow">LIVE / ATXRACING</span><h2>{"Prochain direct" if lang=="fr" else "Next live broadcast"}</h2><p>{"Le direct publié depuis l’administration apparaîtra ici. Twitch reste utilisé pour la diffusion en direct." if lang=="fr" else "The stream published from the administration panel will appear here. Twitch remains the live broadcast platform."}</p><div id="live-media" aria-live="polite"></div></section><section class="replay-stage"><span class="eyebrow">YOUTUBE / ARCHIVES</span><h2>Replays</h2><p>{"Les replays YouTube restent disponibles durablement, contrairement aux VOD Twitch limitées dans le temps." if lang=="fr" else "YouTube replays remain available permanently, unlike time-limited Twitch VODs."}</p><div id="replay-media" class="replay-grid" aria-live="polite"></div></section>'
    if section in ('worldgt','worldgt-sprint','worldgt-endurance','daily-race','atx-series','ballade'):
     desc=FORMATS[lang][section][2]
     main+=f'<section class="format-detail"><span class="eyebrow">{game.upper()} / {escape(t[section])}</span><h2>{escape(t[section])}</h2>{format_detail(lang,section)}<div class="format-actions"><a class="action" href="/{lang}/{game}/calendar.html?type={"WGT" if section.startswith("worldgt") else "ATXS" if section=="atx-series" else "DR"}">{escape(v["calendar"])} ↗</a><a class="pill" href="/{lang}/{game}/ranking.html?type={"WGT" if section.startswith("worldgt") else "ATXS" if section=="atx-series" else "DR"}#points">{escape(v["standings"])} ↗</a></div></section>'
    if section in ('worldgt','worldgt-sprint','worldgt-endurance','daily-race','atx-series','ballade'):main+=f'<div class="section-intro"><span class="eyebrow">{escape(v["calendar"])}</span><h2>{escape(v["next"])}</h2></div><div id="results" aria-live="polite"></div>'
    if section=='calendar':main+='<nav class="event-categories" aria-label="'+escape(v['calendar'])+'">'+''.join(f'<button type="button" data-category="{code}">{escape(label)}</button>' for code,label in [('ALL',v['calendar']),('WGT','WorldGT'),('DR','Daily Race'),('ATXS','ATX Series')])+'</nav>'
    if section=='rules':main+=f'<section class="briefing-access"><div><span class="eyebrow">GOOGLE DRIVE / BRIEFINGS</span><h2>{"Briefings officiels des épreuves" if lang=="fr" else "Official event briefings"}</h2><p>{"Consultez les documents complets et les consignes propres à chaque format avant de prendre la piste." if lang=="fr" else "Review the complete documents and format-specific instructions before joining the track."}</p></div><a class="action" href="https://drive.google.com/drive/folders/{"10Z404U4oYh32rZI_TYcYLmVc4xKqT3lx" if lang=="fr" else "1Hlr_eUqniHAgjax26NN63x47cbNrudbJ"}?usp=drive_link" target="_blank" rel="noopener noreferrer">{"Accéder aux briefings" if lang=="fr" else "Open the briefings"} <span aria-hidden="true">↗</span></a></section><div class="rules-collection">'+''.join(f'<article class="rule-card"><span class="meta">{str(i).zfill(2)} / ACC</span><h2>{escape(name)}</h2><p>{escape(description)}</p></article>' for i,(name,description) in enumerate(RULES[lang],1))+'</div>'
    if section=='rules':
     penalties=PENALTIES[lang]
     main+=f'<section class="penalty-section"><h2>{escape(penalties["title"])}</h2><div class="ranking-table-wrap"><table class="ranking-table"><thead><tr>'+''.join(f'<th>{escape(h)}</th>' for h in penalties['headers'])+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{escape(cell)}</td>' for cell in row)+'</tr>' for row in penalties['rows'])+'</tbody></table></div></section>'
    if section=='pilots':main+=f'<div id="driver-directory" class="driver-directory"><label for="driver-search">{escape(v["search"])}</label><input id="driver-search" type="search" placeholder="{escape(v["search_hint"])}" autocomplete="off"></div>'
    if section=='messages':main+='<section id="messages-app" class="messages-app" aria-live="polite"></section>'
    if section not in ('ranking','rules','privacy','worldgt','worldgt-sprint','worldgt-endurance','daily-race','atx-series','ballade','admin','profile','messages','circuits','live'):main+='<div id="results" aria-live="polite"><p class="loading">…</p></div>'
    if section=='profile' and game=='acc':main+='<div id="results" aria-live="polite"></div>'
  main+=f'<p class="return-link"><a href="/{lang}/">← {escape(t["back"])}</a></p></main>'
  body=main
 out=head+body+footer+'<script src="/assets/public-data.min.js" defer></script><script src="/assets/gate.min.js" defer></script><script src="/assets/community.min.js" defer></script>'+('<script src="/assets/insignia.min.js" defer></script>' if section=='profile' and game=='acc' else '')+('<script src="/assets/circuit-images.min.js" defer></script>' if game=='acc' and section in ('profile','records','circuits','admin') else '')+('<script src="/assets/profile-media.min.js" defer></script>' if section=='profile' and game=='acc' else '')+('<script src="/assets/site.min.js" defer></script>' if game=='acc' and section in ('courses','records','circuits','profile','pilots') else '')+('<script src="/assets/ranking.min.js" defer></script>' if section=='ranking' and game=='acc' else '')+('<script src="/assets/registration.min.js" defer></script><script src="/assets/events.min.js" defer></script>' if game=='acc' and section in ('calendar','archives','event','course','worldgt','worldgt-sprint','worldgt-endurance','daily-race','atx-series','ballade') else '')+('<script src="/assets/media.min.js" defer></script>' if section=='live' else '')+('<script src="/assets/messages.min.js" defer></script>' if section=='messages' else '')+('<script src="/assets/registration.min.js" defer></script><script src="/assets/admin.min.js" defer></script>' if section=='admin' else '')+('<script src="/assets/account.min.js" defer></script>' if game else '')+'</body></html>'
 path=R/lang/(game or '')/('index.html' if section in ('home','league') else section+'.html');write(path,out)
for l in T:
 page(l,'','home')
 page(l,'','about')
 for g in ('acc','ace'):
  for s in ('league','courses','worldgt','worldgt-sprint','worldgt-endurance','daily-race','atx-series','ballade','calendar','ranking','records','circuits','live','archives','event','course','rules','privacy','profile','messages')+(('pilots','admin') if g=='acc' else ()):page(l,g,s)
entry=f'''<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#090b10"><meta name="atx-base" content="{BASE}"><meta name="description" content="Rejoignez le paddock ATXRACING avec Steam. Courses, classements et communauté ACC et ACE."><link rel="canonical" href="{SITE_URL}"><meta property="og:type" content="website"><meta property="og:site_name" content="ATXRACING"><meta property="og:title" content="Bienvenue dans le paddock ATXRACING"><meta property="og:description" content="Courses, classements et communauté sim racing ACC et ACE."><meta property="og:url" content="{SITE_URL}"><meta property="og:image" content="{SITE_URL}assets/landing-banner.jpg"><meta name="twitter:card" content="summary_large_image"><title>Bienvenue / Welcome · ATXRACING</title><link rel="preload" href="/assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="preconnect" href="https://twjpjzalyvbsdpbzhqln.supabase.co" crossorigin><link rel="stylesheet" href="/assets/site.min.css"></head>
<body data-page="entry"><main class="entry"><div class="entry-content">
<section class="entry-french" lang="fr" aria-label="Bienvenue"><p class="entry-kicker">UN COMPTE. VOTRE PLACE SUR LA GRILLE.</p><h1>LE PADDOCK<br>VOUS <em>ATTEND.</em></h1><p class="entry-lead">Connectez-vous avec Steam pour accéder aux courses et créer votre profil pilote.</p></section>
<a class="entry-connect" href="https://twjpjzalyvbsdpbzhqln.supabase.co/functions/v1/auth-steam?return_path={BASE}fr/acc/profile.html" aria-label="Se connecter avec Steam / Sign in with Steam"><span class="entry-steam-icon" aria-hidden="true">●</span><span>Se connecter avec Steam<small lang="en">Sign in with Steam</small></span><span aria-hidden="true">↗</span></a>
<section class="entry-english" lang="en" aria-label="Welcome"><p class="entry-english-lead">Sign in with Steam to access races and create your driver profile.</p><h2>THE PADDOCK <em>AWAITS YOU.</em></h2><p class="entry-english-kicker">ONE ACCOUNT. YOUR PLACE ON THE GRID.</p></section>
<aside class="entry-engineer" data-race-engineer hidden><span class="engineer-pulse" aria-hidden="true"></span><div><strong>INGÉNIEUR DE COURSE / RACE ENGINEER</strong><p class="entry-status" role="status" data-entry-status></p></div></aside></div><p class="entry-games">COMPETIZIONE <span aria-hidden="true">│</span> ASSETTO CORSA EVO</p></main><script src="/assets/entry.min.js" defer></script></body></html>'''
write(R/'index.html',entry)
for g in ('acc','ace'):selector(g)
for l in T:
 for g in ('acc','ace'):
  target=f'/{l}/{g}/atx-series.html'
  write(R/l/g/'ballade.html',f'<!doctype html><html lang="{l}"><head><meta charset="utf-8"><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url={target}"><link rel="canonical" href="{SITE_URL}{l}/{g}/atx-series.html"><title>ATX Series · ATXRACING</title></head><body><a href="{target}">ATX Series</a></body></html>')

public_urls=[SITE_URL]
for lang in T:
 public_urls.append(SITE_URL+lang+'/about.html')
 for game in ('acc','ace'):
  for section in ('','courses.html','worldgt.html','worldgt-sprint.html','worldgt-endurance.html','daily-race.html','atx-series.html','calendar.html','ranking.html','records.html','circuits.html','live.html','archives.html','rules.html'):
   public_urls.append(SITE_URL+lang+'/'+game+'/'+section)
sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{escape(url)}</loc></url>\n' for url in public_urls)+'</urlset>\n'
(R/'sitemap.xml').write_text(sitemap)
(R/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {SITE_URL}sitemap.xml\n')

# GitHub Pages for this repository is configured to publish main / (root).
# Mirror only generated public files there; sources and docs remain in place.
for generated in R.rglob('*'):
 if generated.is_file():
  target=Path(__file__).parent/generated.relative_to(R)
  target.parent.mkdir(parents=True,exist_ok=True)
  shutil.copy2(generated,target)
