"""Visible editorial copy for the two leagues; same structure in every language."""
COPY={
'fr':{
 'home':'Accueil','league_acc':'La compétition GT3, vécue ensemble.','league_ace':'Une nouvelle façon de prendre la piste.','lead_acc':'Courses organisées, résultats officiels et chronos de la communauté ATXRACING sur ACC.','lead_ace':'La ligue ACE prend forme. Retrouvez ici ses courses, ses pilotes et ses classements dès leur ouverture.','explore':'Explorer la ligue','section':'Votre espace de course','formats':'Nos formats ACC','next':'Prochaines courses','schedule':'Calendrier','standings':'Classement officiel','fastest':'Le tour de référence','drivers':'Pilotes','browse':'Découvrir les pilotes','search':'Rechercher un pilote','search_hint':'Nom ou équipe','category':'Catégorie','track':'Circuit','published':'Données publiées','source':'Données du Collector ACC','no_events':'Aucune prochaine course publiée. Revenez bientôt consulter le calendrier.','no_data':'Aucune donnée officielle publiée pour cette rubrique.','unavailable':'Le service des résultats est momentanément indisponible.','ace_pending':'Les courses et résultats ACE apparaîtront après la mise en service du serveur et du collecteur dédiés.','back_acc':'Voir la ligue ACC','join':'S’inscrire','ranking_lead':'Suivez les pilotes et les équipes, catégorie par catégorie. Les points viennent des résultats officiels.','records_lead':'Les meilleurs tours valides, associés au circuit, au pilote et à la voiture utilisée.','profile_lead':'Une identité pilote pour les deux jeux. Retrouvez les performances ACC publiées et, à terme, celles d’ACE.','courses_lead':'Choisissez votre format et retrouvez les prochaines épreuves ATXRACING.','profile_public':'Profil public','discover':'Voir les courses','see_rank':'Voir le classement','see_records':'Explorer les chronos','see_profile':'Voir les pilotes','stage':'ESPACE PILOTE','formats_items':[
 ('World GT Sprint','Deux pilotes par équipage. Deux courses de 60 min et un changement de pilote obligatoire.'),
 ('World GT Endurance','Équipages de 1 à 6 pilotes. Des épreuves longues sur les grands circuits.'),
 ('Daily Race','Course de 60 min. Un arrêt obligatoire entre la 25e et la 35e minute.'),
 ('Ballade ATX','Course mono marque de 90 min. Deux arrêts obligatoires avec pneus et carburant.')],
},
'en':{
 'home':'Home','league_acc':'GT3 racing, together.','league_ace':'A new way to take to the track.','lead_acc':'Organised races, official results and community lap times on ACC.','lead_ace':'The ACE league is taking shape. Its races, drivers and standings will appear here when launched.','explore':'Explore the league','section':'Your racing hub','formats':'ACC race formats','next':'Upcoming races','schedule':'Calendar','standings':'Official standings','fastest':'Reference lap','drivers':'Drivers','browse':'Explore drivers','search':'Search for a driver','search_hint':'Name or team','category':'Category','track':'Track','published':'Published data','source':'ACC Collector data','no_events':'No upcoming race has been published. Check the calendar again soon.','no_data':'No official data has been published for this section.','unavailable':'The results service is temporarily unavailable.','ace_pending':'ACE races and results will appear after its dedicated server and collector go live.','back_acc':'View the ACC league','join':'Register','ranking_lead':'Follow drivers and teams by category. Points come from official results.','records_lead':'The fastest valid laps, with their track, driver and car.','profile_lead':'One driver identity for both games. See published ACC results and, later, ACE results.','courses_lead':'Choose a format and find upcoming ATXRACING events.','profile_public':'Public profile','discover':'View races','see_rank':'View standings','see_records':'Explore records','see_profile':'View drivers','stage':'DRIVER HUB','formats_items':[
 ('World GT Sprint','Two drivers per crew. Two 60-minute races and one mandatory driver change.'),
 ('World GT Endurance','Crews of 1 to 6 drivers. Long-distance events at major circuits.'),
 ('Daily Race','A 60-minute race. One mandatory stop between minutes 25 and 35.'),
 ('Ballade ATX','A 90-minute single-make race. Two mandatory stops with tyres and fuel.')],
},
'de':{
 'home':'Startseite','league_acc':'GT3-Rennsport, gemeinsam erlebt.','league_ace':'Ein neuer Weg auf die Rennstrecke.','lead_acc':'Organisierte Rennen, offizielle Ergebnisse und Rundenzeiten der ATXRACING-Community in ACC.','lead_ace':'Die ACE-Liga entsteht. Rennen, Fahrer und Wertungen erscheinen hier zum Start.','explore':'Liga entdecken','section':'Dein Rennbereich','formats':'ACC-Rennformate','next':'Nächste Rennen','schedule':'Kalender','standings':'Offizielle Wertung','fastest':'Referenzrunde','drivers':'Fahrer','browse':'Fahrer entdecken','search':'Fahrer suchen','search_hint':'Name oder Team','category':'Kategorie','track':'Strecke','published':'Veröffentlichte Daten','source':'Daten des ACC Collectors','no_events':'Derzeit ist kein kommendes Rennen veröffentlicht. Schau bald wieder vorbei.','no_data':'Für diesen Bereich liegen noch keine offiziellen Daten vor.','unavailable':'Der Ergebnisdienst ist vorübergehend nicht erreichbar.','ace_pending':'ACE-Rennen und Ergebnisse erscheinen nach dem Start des eigenen Servers und Collectors.','back_acc':'ACC-Liga ansehen','join':'Anmelden','ranking_lead':'Fahrer und Teams nach Kategorie verfolgen. Die Punkte stammen aus offiziellen Ergebnissen.','records_lead':'Die schnellsten gültigen Runden mit Strecke, Fahrer und Fahrzeug.','profile_lead':'Eine Fahreridentität für beide Spiele. Veröffentlichte ACC-Ergebnisse und später auch ACE-Ergebnisse.','courses_lead':'Wähle ein Format und entdecke die nächsten ATXRACING-Rennen.','profile_public':'Öffentliches Profil','discover':'Rennen ansehen','see_rank':'Wertung ansehen','see_records':'Bestzeiten ansehen','see_profile':'Fahrer ansehen','stage':'FAHRERBEREICH','formats_items':[
 ('World GT Sprint','Zwei Fahrer pro Team. Zwei Rennen à 60 Minuten mit vorgeschriebenem Fahrerwechsel.'),
 ('World GT Endurance','Teams mit 1 bis 6 Fahrern. Langstreckenrennen auf großen Rennstrecken.'),
 ('Daily Race','Rennen über 60 Minuten. Ein Pflichtstopp zwischen Minute 25 und 35.'),
 ('Ballade ATX','Markenpokalrennen über 90 Minuten. Zwei Pflichtstopps mit Reifen und Betankung.')],
},
'it':{
 'home':'Home','league_acc':'Le gare GT3, insieme.','league_ace':'Un nuovo modo di scendere in pista.','lead_acc':'Gare organizzate, risultati ufficiali e tempi sul giro della comunità ATXRACING in ACC.','lead_ace':'La lega ACE prende forma. Gare, piloti e classifiche appariranno qui all’avvio.','explore':'Scopri la lega','section':'Il tuo spazio corse','formats':'Formati di gara ACC','next':'Prossime gare','schedule':'Calendario','standings':'Classifica ufficiale','fastest':'Giro di riferimento','drivers':'Piloti','browse':'Scopri i piloti','search':'Cerca un pilota','search_hint':'Nome o squadra','category':'Categoria','track':'Circuito','published':'Dati pubblicati','source':'Dati dell’ACC Collector','no_events':'Non ci sono ancora gare future pubblicate. Controlla di nuovo il calendario.','no_data':'Non ci sono ancora dati ufficiali pubblicati per questa sezione.','unavailable':'Il servizio dei risultati è temporaneamente non disponibile.','ace_pending':'Gare e risultati ACE appariranno dopo l’avvio del server e del collector dedicati.','back_acc':'Vai alla lega ACC','join':'Iscriviti','ranking_lead':'Segui piloti e squadre per categoria. I punti provengono dai risultati ufficiali.','records_lead':'I giri validi più veloci, con circuito, pilota e auto utilizzata.','profile_lead':'Un’unica identità pilota per entrambi i giochi. Risultati ACC pubblicati e, in futuro, risultati ACE.','courses_lead':'Scegli un formato e scopri le prossime gare ATXRACING.','profile_public':'Profilo pubblico','discover':'Vedi le gare','see_rank':'Vedi la classifica','see_records':'Esplora i record','see_profile':'Vedi i piloti','stage':'SPAZIO PILOTI','formats_items':[
 ('World GT Sprint','Due piloti per equipaggio. Due gare di 60 minuti e un cambio pilota obbligatorio.'),
 ('World GT Endurance','Equipaggi da 1 a 6 piloti. Gare di durata sui grandi circuiti.'),
 ('Daily Race','Gara di 60 minuti. Una sosta obbligatoria tra il 25° e il 35° minuto.'),
 ('Ballade ATX','Gara monomarca di 90 minuti. Due soste obbligatorie con gomme e carburante.')],
},
'es':{
 'home':'Inicio','league_acc':'Competición GT3, juntos.','league_ace':'Una nueva forma de salir a pista.','lead_acc':'Carreras organizadas, resultados oficiales y tiempos por vuelta de la comunidad ATXRACING en ACC.','lead_ace':'La liga ACE está tomando forma. Sus carreras, pilotos y clasificaciones aparecerán aquí al comenzar.','explore':'Explorar la liga','section':'Tu espacio de competición','formats':'Formatos de carrera ACC','next':'Próximas carreras','schedule':'Calendario','standings':'Clasificación oficial','fastest':'Vuelta de referencia','drivers':'Pilotos','browse':'Descubrir pilotos','search':'Buscar piloto','search_hint':'Nombre o equipo','category':'Categoría','track':'Circuito','published':'Datos publicados','source':'Datos del ACC Collector','no_events':'Aún no hay carreras futuras publicadas. Vuelve a consultar el calendario.','no_data':'Todavía no hay datos oficiales publicados para esta sección.','unavailable':'El servicio de resultados no está disponible temporalmente.','ace_pending':'Las carreras y resultados ACE aparecerán cuando se activen su servidor y collector dedicados.','back_acc':'Ver la liga ACC','join':'Inscribirse','ranking_lead':'Sigue a pilotos y equipos por categoría. Los puntos proceden de resultados oficiales.','records_lead':'Las vueltas válidas más rápidas, con circuito, piloto y coche utilizado.','profile_lead':'Una sola identidad de piloto para ambos juegos. Resultados ACC publicados y, más adelante, de ACE.','courses_lead':'Elige un formato y descubre los próximos eventos ATXRACING.','profile_public':'Perfil público','discover':'Ver carreras','see_rank':'Ver clasificación','see_records':'Explorar tiempos','see_profile':'Ver pilotos','stage':'ESPACIO PILOTOS','formats_items':[
 ('World GT Sprint','Dos pilotos por equipo. Dos carreras de 60 minutos y un cambio de piloto obligatorio.'),
 ('World GT Endurance','Equipos de 1 a 6 pilotos. Pruebas de resistencia en grandes circuitos.'),
 ('Daily Race','Carrera de 60 minutos. Una parada obligatoria entre los minutos 25 y 35.'),
 ('Ballade ATX','Carrera monomarca de 90 minutos. Dos paradas obligatorias con neumáticos y combustible.')],
}}

RANKING_UI = {
 'fr': dict(points_view='Points par catégorie', circuit_view='Classement par circuit', driver_view='Parcours par pilote', team_view='Classement des équipes'),
 'en': dict(points_view='Points by category', circuit_view='Standings by circuit', driver_view='Driver performance', team_view='Team standings'),
 'de': dict(points_view='Punkte nach Kategorie', circuit_view='Wertung nach Strecke', driver_view='Fahrerleistungen', team_view='Teamwertung'),
 'it': dict(points_view='Punti per categoria', circuit_view='Classifica per circuito', driver_view='Percorso del pilota', team_view='Classifica squadre'),
 'es': dict(points_view='Puntos por categoría', circuit_view='Clasificación por circuito', driver_view='Trayectoria del piloto', team_view='Clasificación por equipos'),
}

EXTRA = {
 'fr':dict(calendar='Calendrier',archives='Archives',event='Course',rules='Règlement',calendar_lead='Le programme ATXRACING, par format et par date. Retrouvez les affiches et l’inscription à chaque course.',archives_lead='Les courses terminées, leurs résultats et les performances publiées.',event_lead='Détails de course et résultats officiels.',rules_lead='Les règles sportives communes à toutes les courses ACC. Les indications propres à un événement figurent sur sa page.',formats_short='Choisissez un format pour découvrir ses courses.',register='S’inscrire sur SimGrid',results='Résultats',teams='Équipes',drivers='Pilotes'),
 'en':dict(calendar='Calendar',archives='Archives',event='Race',rules='Rules',calendar_lead='The ATXRACING schedule by format and date. See posters and register for each race.',archives_lead='Completed races, results and published performances.',event_lead='Race details and official results.',rules_lead='Sporting rules common to all ACC races. Event-specific details appear on its page.',formats_short='Choose a format and explore its races.',register='Register on SimGrid',results='Results',teams='Teams',drivers='Drivers'),
 'de':dict(calendar='Kalender',archives='Archiv',event='Rennen',rules='Reglement',calendar_lead='Der ATXRACING-Rennplan nach Format und Datum. Plakate und Anmeldung zu jedem Rennen.',archives_lead='Abgeschlossene Rennen, Ergebnisse und veröffentlichte Leistungen.',event_lead='Renndetails und offizielle Ergebnisse.',rules_lead='Sportliche Regeln für alle ACC-Rennen. Besondere Vorgaben stehen auf der Veranstaltungsseite.',formats_short='Wähle ein Format und entdecke seine Rennen.',register='Auf SimGrid anmelden',results='Ergebnisse',teams='Teams',drivers='Fahrer'),
 'it':dict(calendar='Calendario',archives='Archivio',event='Gara',rules='Regolamento',calendar_lead='Il programma ATXRACING per formato e data. Locandine e iscrizioni per ogni gara.',archives_lead='Gare concluse, risultati e prestazioni pubblicate.',event_lead='Dettagli gara e risultati ufficiali.',rules_lead='Regole sportive valide per tutte le gare ACC. Le indicazioni specifiche sono nella pagina dell’evento.',formats_short='Scegli un formato e scopri le gare.',register='Iscriviti su SimGrid',results='Risultati',teams='Squadre',drivers='Piloti'),
 'es':dict(calendar='Calendario',archives='Archivo',event='Carrera',rules='Reglamento',calendar_lead='El programa ATXRACING por formato y fecha. Carteles e inscripción de cada carrera.',archives_lead='Carreras terminadas, resultados y actuaciones publicadas.',event_lead='Detalles de carrera y resultados oficiales.',rules_lead='Normas deportivas para todas las carreras ACC. Las indicaciones específicas figuran en cada evento.',formats_short='Elige un formato y descubre sus carreras.',register='Inscribirse en SimGrid',results='Resultados',teams='Equipos',drivers='Pilotos'),
}

RULES = {
 'fr':[
 ('Conduite en piste','Pilotez avec respect et prévisibilité. Contacts évitables, changements de trajectoire dangereux, freinages volontaires et manœuvres antisportives sont interdits.'),
 ('Départ et premier virage','Adaptez votre freinage au trafic et respectez les voitures à vos côtés. Une collision volontaire peut entraîner une disqualification immédiate.'),
 ('Intervention de la direction de course','Si plusieurs voitures sont impliquées dans un accident dans les trois premiers virages, la direction de course peut ordonner un seul redémarrage. Un message VSC impose alors le limiteur et 50 km/h maximum.'),
 ('WGT Sprint','Deux pilotes par équipage, deux manches de 60 minutes. Un arrêt avec changement de pilote est obligatoire ; le stint ne dépasse pas 35 minutes. Pneus et carburant facultatifs.'),
 ('WGT Endurance','De 1 à 6 pilotes par équipage. Le stint maximum est de 45 minutes par pilote ; la stratégie de pneus et de carburant appartient à l’équipe.'),
 ('Daily Race','Une course de 60 minutes et un arrêt obligatoire entre la 25e et la 35e minute. Pneus et carburant facultatifs.'),
 ('Ballade ATX','Course mono marque de 90 minutes, deux arrêts obligatoires avec changement de pneus et ravitaillement.'),
 ('Après un incident','Reprenez la piste uniquement lorsque cela ne gêne personne. Respectez les drapeaux bleus. Les réclamations passent par la procédure SimGrid de la course concernée.'),('Inscription et résultats','28 pilotes maximum ; ATXRACING réserve au moins un emplacement technique au commissaire. Les résultats deviennent officiels après examen des incidents.'),('Pénalités tardives','Un Drive Through attribué trop tard pour être exécuté est converti en 30 secondes. Un incident grave peut justifier une sanction plus élevée ; sans preuve suffisante, aucune sanction n’est appliquée.')],
 'en':[
 ('Driving standards','Race respectfully and predictably. Avoidable contact, dangerous line changes, deliberate braking and unsporting moves are prohibited.'),('Start and first corner','Adjust braking for traffic and respect cars alongside. A deliberate collision may lead to immediate disqualification.'),('Race control','After a multi-car crash in the first three corners, race control may order one restart. A VSC message then requires the pit limiter and a maximum speed of 50 km/h.'),('WGT Sprint','Two drivers per crew and two 60-minute races. One stop with a driver change is required; stints are limited to 35 minutes. Tyres and fuel are optional.'),('WGT Endurance','Crews of 1 to 6 drivers. Each stint is limited to 45 minutes; tyre and fuel strategy is up to the crew.'),('Daily Race','A 60-minute race and one mandatory stop between minutes 25 and 35. Tyres and fuel are optional.'),('Ballade ATX','A 90-minute single-make race with two mandatory stops, tyre changes and refuelling.'),('After an incident','Rejoin only when safe and respect blue flags. Submit protests via the event’s SimGrid procedure.'),('Registration and results','Maximum 28 drivers; ATXRACING reserves at least one technical slot for the steward. Results become official after incidents have been reviewed.'),('Late penalties','A Drive Through imposed too late to serve converts to 30 seconds. Serious incidents may justify a higher penalty; insufficient evidence means no penalty.')],
 'de':[
 ('Fahrverhalten','Fahre respektvoll und berechenbar. Vermeidbare Berührungen, gefährliche Spurwechsel, absichtliches Bremsen und unsportliche Manöver sind untersagt.'),('Start und erste Kurve','Passe den Bremspunkt dem Verkehr an und respektiere Fahrzeuge neben dir. Ein absichtlicher Unfall kann zur sofortigen Disqualifikation führen.'),('Rennleitung','Nach einem Unfall mit mehreren Fahrzeugen in den ersten drei Kurven kann die Rennleitung einmal neu starten. Eine VSC-Meldung schreibt dann den Begrenzer und höchstens 50 km/h vor.'),('WGT Sprint','Zwei Fahrer pro Team, zwei Rennen à 60 Minuten. Ein Stopp mit Fahrerwechsel ist Pflicht; ein Stint dauert höchstens 35 Minuten. Reifen und Kraftstoff sind optional.'),('WGT Endurance','Teams mit 1 bis 6 Fahrern. Ein Stint dauert höchstens 45 Minuten; Reifen- und Kraftstoffstrategie bestimmt das Team.'),('Daily Race','Rennen über 60 Minuten mit einem Pflichtstopp zwischen Minute 25 und 35. Reifen und Kraftstoff sind optional.'),('Ballade ATX','Markenpokalrennen über 90 Minuten mit zwei Pflichtstopps, Reifenwechsel und Betankung.'),('Nach einem Zwischenfall','Kehre nur sicher auf die Strecke zurück und beachte blaue Flaggen. Proteste werden über SimGrid für das jeweilige Rennen eingereicht.'),('Anmeldung und Ergebnisse','Höchstens 28 Fahrer; ATXRACING reserviert mindestens einen technischen Platz für die Rennleitung. Ergebnisse werden nach Prüfung der Zwischenfälle offiziell.'),('Späte Strafen','Eine nicht mehr ausführbare Durchfahrtsstrafe wird in 30 Sekunden umgewandelt. Schwere Vorfälle können höhere Strafen begründen; ohne ausreichende Beweise gibt es keine Strafe.')],
 'it':[
 ('Condotta in pista','Guida con rispetto e prevedibilità. Sono vietati contatti evitabili, cambi di traiettoria pericolosi, frenate intenzionali e manovre antisportive.'),('Partenza e prima curva','Adegua la frenata al traffico e rispetta le auto affiancate. Un incidente volontario può comportare la squalifica immediata.'),('Direzione gara','Dopo un incidente multiplo nelle prime tre curve, la direzione gara può disporre un solo riavvio. Un messaggio VSC impone il limitatore e una velocità massima di 50 km/h.'),('WGT Sprint','Due piloti per equipaggio e due gare di 60 minuti. Obbligatoria una sosta con cambio pilota; ogni stint dura al massimo 35 minuti. Pneumatici e carburante facoltativi.'),('WGT Endurance','Equipaggi da 1 a 6 piloti. Ogni stint dura al massimo 45 minuti; strategia di pneumatici e carburante libera.'),('Daily Race','Gara di 60 minuti con una sosta obbligatoria tra il 25° e il 35° minuto. Pneumatici e carburante facoltativi.'),('Ballade ATX','Gara monomarca di 90 minuti con due soste obbligatorie, cambio gomme e rifornimento.'),('Dopo un incidente','Rientra in pista solo quando è sicuro e rispetta le bandiere blu. I reclami passano dalla procedura SimGrid della gara.'),('Iscrizione e risultati','Massimo 28 piloti; ATXRACING riserva almeno uno slot tecnico al commissario. I risultati diventano ufficiali dopo l’esame degli incidenti.'),('Penalità tardive','Un Drive Through non più eseguibile è convertito in 30 secondi. Incidenti gravi possono giustificare sanzioni maggiori; senza prove sufficienti non si applicano penalità.')],
 'es':[
 ('Conducta en pista','Conduce con respeto y de forma previsible. Se prohíben los contactos evitables, cambios de trayectoria peligrosos, frenadas deliberadas y maniobras antideportivas.'),('Salida y primera curva','Adapta la frenada al tráfico y respeta los coches que circulan a tu lado. Una colisión intencionada puede causar la descalificación inmediata.'),('Dirección de carrera','Tras un accidente múltiple en las tres primeras curvas, dirección de carrera puede ordenar un único reinicio. Un aviso VSC obliga a usar el limitador y no superar 50 km/h.'),('WGT Sprint','Dos pilotos por equipo y dos carreras de 60 minutos. Es obligatoria una parada con cambio de piloto; cada stint dura como máximo 35 minutos. Neumáticos y combustible opcionales.'),('WGT Endurance','Equipos de 1 a 6 pilotos. Cada stint dura como máximo 45 minutos; la estrategia de neumáticos y combustible es libre.'),('Daily Race','Carrera de 60 minutos con una parada obligatoria entre los minutos 25 y 35. Neumáticos y combustible opcionales.'),('Ballade ATX','Carrera monomarca de 90 minutos con dos paradas obligatorias, cambio de neumáticos y repostaje.'),('Después de un incidente','Vuelve a pista solo cuando sea seguro y respeta las banderas azules. Las reclamaciones se presentan mediante SimGrid en el evento correspondiente.'),('Inscripción y resultados','Máximo 28 pilotos; ATXRACING reserva al menos una plaza técnica para el comisario. Los resultados son oficiales tras revisar los incidentes.'),('Sanciones tardías','Un Drive Through imposible de cumplir se convierte en 30 segundos. Los incidentes graves pueden justificar penas mayores; sin pruebas suficientes no se sanciona.')],
}

PENALTIES = {
 'fr':{'title':'Barème des sanctions','headers':['Infraction confirmée','1re','2e','3e'],'rows':[
  ('Ligne blanche à la sortie des stands','+10 s','Drive Through','Disqualification'),('Drapeau bleu ignoré','+10 s','Drive Through','Disqualification'),('Accident avec responsabilité confirmée','+10 s','Drive Through','Disqualification'),('Retour dangereux en piste','+10 s','Drive Through','Disqualification'),('Retour dangereux provoquant un accident','Drive Through','Disqualification','Exclusion possible'),('Changement de trajectoire au freinage','+10 s','Drive Through','Disqualification'),('Concurrent poussé hors piste','+10 s','Drive Through','Disqualification'),('Obstruction volontaire en qualification','+5 s','+30 s','Disqualification'),('Instruction de course ignorée','Drive Through','Disqualification','Exclusion possible'),('Collision volontaire ou vengeance','Disqualification immédiate','Suspension possible','Exclusion possible'),('Insultes ou comportement antisportif','Avertissement','Exclusion de l’événement','Suspension possible')]},
 'en':{'title':'Penalty scale','headers':['Confirmed infringement','1st','2nd','3rd'],'rows':[
  ('Crossing the pit exit line','+10 s','Drive Through','Disqualification'),('Ignoring a blue flag','+10 s','Drive Through','Disqualification'),('Collision with confirmed fault','+10 s','Drive Through','Disqualification'),('Unsafe rejoin','+10 s','Drive Through','Disqualification'),('Unsafe rejoin causing a crash','Drive Through','Disqualification','Possible exclusion'),('Changing line under braking','+10 s','Drive Through','Disqualification'),('Forcing a competitor off track','+10 s','Drive Through','Disqualification'),('Deliberate obstruction in qualifying','+5 s','+30 s','Disqualification'),('Ignoring race control instructions','Drive Through','Disqualification','Possible exclusion'),('Deliberate collision or retaliation','Immediate disqualification','Possible suspension','Possible exclusion'),('Abuse or unsporting conduct','Warning','Event exclusion','Possible suspension')]},
 'de':{'title':'Strafenkatalog','headers':['Bestätigter Verstoß','1. Mal','2. Mal','3. Mal'],'rows':[
  ('Weiße Linie an der Boxenausfahrt','+10 s','Durchfahrtsstrafe','Disqualifikation'),('Blaue Flagge missachtet','+10 s','Durchfahrtsstrafe','Disqualifikation'),('Verschuldeter Unfall','+10 s','Durchfahrtsstrafe','Disqualifikation'),('Gefährliche Rückkehr auf die Strecke','+10 s','Durchfahrtsstrafe','Disqualifikation'),('Gefährliche Rückkehr mit Unfallfolge','Durchfahrtsstrafe','Disqualifikation','Ausschluss möglich'),('Spurwechsel beim Bremsen','+10 s','Durchfahrtsstrafe','Disqualifikation'),('Gegner von der Strecke gedrängt','+10 s','Durchfahrtsstrafe','Disqualifikation'),('Absichtliche Behinderung im Qualifying','+5 s','+30 s','Disqualifikation'),('Rennleitung missachtet','Durchfahrtsstrafe','Disqualifikation','Ausschluss möglich'),('Absichtliche Kollision oder Vergeltung','Sofortige Disqualifikation','Sperre möglich','Ausschluss möglich'),('Beleidigung oder unsportliches Verhalten','Verwarnung','Ausschluss vom Rennen','Sperre möglich')]},
 'it':{'title':'Tabella delle penalità','headers':['Infrazione accertata','1ª','2ª','3ª'],'rows':[
  ('Linea bianca all’uscita box','+10 s','Drive Through','Squalifica'),('Bandiera blu ignorata','+10 s','Drive Through','Squalifica'),('Incidente con responsabilità accertata','+10 s','Drive Through','Squalifica'),('Rientro pericoloso in pista','+10 s','Drive Through','Squalifica'),('Rientro pericoloso con incidente','Drive Through','Squalifica','Possibile esclusione'),('Cambio traiettoria in frenata','+10 s','Drive Through','Squalifica'),('Avversario spinto fuori pista','+10 s','Drive Through','Squalifica'),('Ostruzione volontaria in qualifica','+5 s','+30 s','Squalifica'),('Istruzioni della direzione ignorate','Drive Through','Squalifica','Possibile esclusione'),('Collisione volontaria o vendetta','Squalifica immediata','Possibile sospensione','Possibile esclusione'),('Insulti o condotta antisportiva','Ammonimento','Esclusione dall’evento','Possibile sospensione')]},
 'es':{'title':'Escala de sanciones','headers':['Infracción confirmada','1.ª','2.ª','3.ª'],'rows':[
  ('Línea blanca a la salida de boxes','+10 s','Drive Through','Descalificación'),('Bandera azul ignorada','+10 s','Drive Through','Descalificación'),('Accidente con culpa confirmada','+10 s','Drive Through','Descalificación'),('Reincorporación peligrosa','+10 s','Drive Through','Descalificación'),('Reincorporación peligrosa con accidente','Drive Through','Descalificación','Posible exclusión'),('Cambio de trayectoria al frenar','+10 s','Drive Through','Descalificación'),('Rival empujado fuera de pista','+10 s','Drive Through','Descalificación'),('Obstrucción voluntaria en clasificación','+5 s','+30 s','Descalificación'),('Instrucciones de dirección ignoradas','Drive Through','Descalificación','Posible exclusión'),('Colisión intencionada o venganza','Descalificación inmediata','Posible suspensión','Posible exclusión'),('Insultos o conducta antideportiva','Advertencia','Exclusión del evento','Posible suspensión')]},
}

FORMATS = {
 'fr':{
  'worldgt':('WorldGT','Le championnat GT3 ATXRACING : équipages, sprint et endurance.','Sprint : deux pilotes, deux manches de 60 minutes et un arrêt avec changement de pilote. Endurance : de 1 à 6 pilotes et un stint de 45 minutes maximum.'),
  'daily-race':('Daily Race','Une course GT3 ouverte à la communauté, avec un rythme régulier.','60 minutes de course et un arrêt obligatoire entre les 25e et 35e minutes. Pneus et carburant facultatifs.'),
  'ballade':('Ballade ATX','Le rendez-vous mono marque pour partager la piste.','90 minutes, deux arrêts obligatoires, changement de pneus et ravitaillement en carburant.')},
 'en':{
  'worldgt':('WorldGT','ATXRACING’s GT3 championship: crews, sprint and endurance.','Sprint: two drivers, two 60-minute races and a mandatory driver-change stop. Endurance: crews of 1 to 6 with a maximum 45-minute stint.'),
  'daily-race':('Daily Race','A community GT3 race with a regular competitive rhythm.','60 minutes of racing and one mandatory stop between minutes 25 and 35. Tyres and fuel are optional.'),
  'ballade':('Ballade ATX','The single-make event for enjoying the track together.','90 minutes, two mandatory stops, tyre changes and refuelling.')},
 'de':{
  'worldgt':('WorldGT','Die GT3-Meisterschaft von ATXRACING: Teams, Sprint und Langstrecke.','Sprint: zwei Fahrer, zwei Rennen à 60 Minuten und ein Pflichtstopp mit Fahrerwechsel. Langstrecke: Teams mit 1 bis 6 Fahrern, Stints bis 45 Minuten.'),
  'daily-race':('Daily Race','Ein GT3-Rennen für die Community mit regelmäßigem Wettbewerb.','60 Minuten Rennzeit und ein Pflichtstopp zwischen Minute 25 und 35. Reifen und Kraftstoff sind optional.'),
  'ballade':('Ballade ATX','Das Markenpokalrennen für gemeinsames Fahren.','90 Minuten, zwei Pflichtstopps, Reifenwechsel und Betankung.')},
 'it':{
  'worldgt':('WorldGT','Il campionato GT3 ATXRACING: equipaggi, sprint e durata.','Sprint: due piloti, due gare da 60 minuti e una sosta con cambio pilota. Endurance: equipaggi da 1 a 6 piloti e stint di massimo 45 minuti.'),
  'daily-race':('Daily Race','Una gara GT3 aperta alla comunità con appuntamenti regolari.','60 minuti di gara e una sosta obbligatoria tra il 25° e il 35° minuto. Gomme e carburante facoltativi.'),
  'ballade':('Ballade ATX','L’evento monomarca per condividere la pista.','90 minuti, due soste obbligatorie, cambio gomme e rifornimento.')},
 'es':{
  'worldgt':('WorldGT','El campeonato GT3 ATXRACING: equipos, sprint y resistencia.','Sprint: dos pilotos, dos carreras de 60 minutos y una parada con cambio de piloto. Resistencia: equipos de 1 a 6 pilotos con stints de máximo 45 minutos.'),
  'daily-race':('Daily Race','Una carrera GT3 abierta a la comunidad con competición regular.','60 minutos y una parada obligatoria entre los minutos 25 y 35. Neumáticos y combustible opcionales.'),
  'ballade':('Ballade ATX','La cita monomarca para compartir pista.','90 minutos, dos paradas obligatorias, cambio de neumáticos y repostaje.')},
}

PRIVACY = {
 'fr':{'title':'Confidentialité','lead':'Les données utilisées pour le compte pilote, les résultats et les classements ATXRACING.','parts':[
 ('Responsable et contact','ATX Racing, branche événementielle d’ATX Motorsport, traite les données de la plateforme. Pour toute question ou demande : athoxmotorsport@gmail.com.'),
 ('Données traitées','La connexion Steam fournit votre identifiant Steam ID64, pseudo, URL de profil et avatar publics. Vous pouvez ajouter une équipe, un pays, un numéro, une présentation, une photo et des liens. Le Collector ACC reçoit aussi les résultats et données de conduite des courses.'),
 ('Finalités et bases juridiques','L’authentification permet de fournir le service demandé (RGPD 6.1.b). La publication des résultats, la fiabilité sportive et la prévention des abus reposent sur l’intérêt légitime (6.1.f). Les informations de présentation facultatives reposent sur votre consentement (6.1.a).'),
 ('Publication et niveaux','Les courses publiques peuvent afficher pseudos, voitures, chronos, classements et statistiques. Les niveaux Performance et SAFE sont des indicateurs sportifs calculés automatiquement. Signalez toute erreur pour demander une vérification.'),
 ('Prestataires','Supabase héberge les données et les fonctions ; GitHub Pages diffuse les pages publiques ; Valve/Steam fournit l’identification. Leurs propres politiques et éventuels transferts internationaux peuvent s’appliquer.'),
 ('Conservation et sécurité','Les sessions expirent après 7 jours. Les profils actifs et résultats sportifs peuvent rester nécessaires aux archives de ligue. Les jetons sont hachés côté serveur ; l’accès aux fonctions privées demande une session valide.'),
 ('Vos droits','Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, la portabilité ou vous opposer à certains traitements. Vous pouvez retirer votre consentement pour les informations facultatives. Contactez-nous pour exercer ces droits.'),
 ('Réclamation','Vous pouvez contacter l’Autorité de protection des données belge ou une autorité compétente dans votre pays de résidence.'),
 ('Stockage local','La langue choisie apparaît dans l’adresse. Le jeton de connexion est conservé dans le stockage de session du navigateur ; l’aide initiale du profil mémorise votre choix dans le stockage local. Nous n’utilisons pas de publicité ciblée.'),
 ('Modifications','Cette information peut évoluer avec le site et ses fonctionnalités. Vérifiez la version publiée pour connaître la politique en vigueur.')],
 },
 'en':{'title':'Privacy','lead':'How ATXRACING uses driver account, race result and ranking data.','parts':[
 ('Controller and contact','ATX Racing, the event division of ATX Motorsport, processes platform data. For questions or requests: athoxmotorsport@gmail.com.'),('Data processed','Steam sign-in provides your public Steam ID64, name, profile URL and avatar. You may add a team, country, number, biography, photo and links. The ACC Collector also receives race results and driving data.'),('Purposes and legal bases','Authentication provides the requested service (GDPR Article 6(1)(b)). Publishing results, sporting integrity and abuse prevention rely on legitimate interest (6(1)(f)). Optional profile information relies on consent (6(1)(a)).'),('Publication and ratings','Public races may display names, cars, lap times, rankings and statistics. Performance and SAFE are automatically calculated sporting indicators. Report an error to request a review.'),('Providers','Supabase hosts data and functions, GitHub Pages serves the public pages, and Valve/Steam provides identification. Their own policies and possible international transfers may apply.'),('Retention and security','Sessions expire after 7 days. Active profiles and sporting results may be retained for league archives. Tokens are hashed on the server; private functions require a valid session.'),('Your rights','You may request access, correction, erasure, restriction, portability or object to certain processing. You may withdraw consent for optional information. Contact us to exercise these rights.'),('Complaints','You may contact the Belgian Data Protection Authority or a competent authority in your country of residence.'),('Local storage','The selected language is reflected in the URL. A sign-in token is stored in browser session storage; the initial profile guide remembers your choice in local storage. We do not use targeted advertising.'),('Changes','This notice may change as the site develops. Check the published version for the current policy.')],
 },
 'de':{'title':'Datenschutz','lead':'Wie ATXRACING Daten zu Fahrerprofil, Rennergebnissen und Wertungen verwendet.','parts':[
 ('Verantwortlicher und Kontakt','ATX Racing, die Eventabteilung von ATX Motorsport, verarbeitet Plattformdaten. Kontakt: athoxmotorsport@gmail.com.'),('Verarbeitete Daten','Die Steam-Anmeldung liefert öffentliche Steam ID64, Profilnamen, URL und Avatar. Freiwillig können Team, Land, Startnummer, Beschreibung, Foto und Links ergänzt werden. Der ACC Collector erhält Rennergebnisse und Fahrdaten.'),('Zwecke und Rechtsgrundlagen','Die Anmeldung ermöglicht den angeforderten Dienst (DSGVO Art. 6 Abs. 1 b). Ergebnisse, sportliche Integrität und Missbrauchsschutz beruhen auf berechtigtem Interesse (f). Freiwillige Profilangaben beruhen auf Einwilligung (a).'),('Veröffentlichung und Einstufung','Öffentliche Rennen können Namen, Fahrzeuge, Rundenzeiten, Wertungen und Statistiken zeigen. Performance und SAFE sind automatisch berechnete sportliche Hinweise. Fehler können zur Prüfung gemeldet werden.'),('Dienstleister','Supabase hostet Daten und Funktionen, GitHub Pages die öffentlichen Seiten, Valve/Steam stellt die Anmeldung bereit. Eigene Richtlinien und mögliche internationale Übermittlungen gelten.'),('Speicherung und Sicherheit','Sitzungen laufen nach 7 Tagen ab. Aktive Profile und Sportergebnisse können für das Ligaarchiv aufbewahrt werden. Token werden serverseitig gehasht; private Funktionen erfordern eine gültige Sitzung.'),('Ihre Rechte','Sie können Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit verlangen oder bestimmten Verarbeitungen widersprechen. Einwilligung für freiwillige Angaben kann widerrufen werden.'),('Beschwerden','Sie können die belgische Datenschutzbehörde oder die zuständige Behörde Ihres Wohnsitzlandes kontaktieren.'),('Lokale Speicherung','Die Sprache steht in der URL. Das Anmeldetoken liegt im Sitzungsspeicher; die Starthilfe zum Profil merkt sich Ihre Wahl lokal. Keine zielgerichtete Werbung.'),('Änderungen','Diese Hinweise können mit den Funktionen der Website angepasst werden. Maßgeblich ist die veröffentlichte Fassung.')],
 },
 'it':{'title':'Privacy','lead':'Come ATXRACING utilizza dati di profilo, risultati e classifiche.','parts':[
 ('Titolare e contatti','ATX Racing, divisione eventi di ATX Motorsport, tratta i dati della piattaforma. Contatto: athoxmotorsport@gmail.com.'),('Dati trattati','Steam fornisce ID64, nome, URL e avatar pubblici. Puoi aggiungere squadra, paese, numero, biografia, foto e link. Il Collector ACC riceve risultati di gara e dati di guida.'),('Finalità e basi giuridiche','L’accesso consente il servizio richiesto (GDPR art. 6(1)(b)). Risultati, integrità sportiva e prevenzione degli abusi si fondano sul legittimo interesse (f). I dati facoltativi del profilo sul consenso (a).'),('Pubblicazione e livelli','Le gare pubbliche possono mostrare nomi, auto, tempi, classifiche e statistiche. Performance e SAFE sono indicatori sportivi calcolati automaticamente. Segnala errori per richiedere una verifica.'),('Fornitori','Supabase ospita dati e funzioni, GitHub Pages le pagine pubbliche e Valve/Steam l’identificazione. Possono applicarsi politiche proprie e trasferimenti internazionali.'),('Conservazione e sicurezza','Le sessioni scadono dopo 7 giorni. Profili attivi e risultati possono essere conservati negli archivi della lega. I token sono sottoposti a hash sul server; le funzioni private richiedono una sessione valida.'),('I tuoi diritti','Puoi richiedere accesso, rettifica, cancellazione, limitazione, portabilità od opporti a determinati trattamenti. Puoi revocare il consenso per i dati facoltativi.'),('Reclami','Puoi contattare l’autorità belga per la protezione dei dati o quella competente nel tuo paese.'),('Archiviazione locale','La lingua è indicata nell’URL. Il token è nella memoria di sessione; la guida iniziale del profilo ricorda la scelta nella memoria locale. Nessuna pubblicità mirata.'),('Modifiche','Questa informativa può cambiare con le funzionalità del sito. Fa fede la versione pubblicata.')],
 },
 'es':{'title':'Privacidad','lead':'Cómo utiliza ATXRACING los datos del perfil, resultados y clasificaciones.','parts':[
 ('Responsable y contacto','ATX Racing, división de eventos de ATX Motorsport, trata los datos de la plataforma. Contacto: athoxmotorsport@gmail.com.'),('Datos tratados','Steam proporciona ID64, nombre, URL y avatar públicos. Puedes añadir equipo, país, número, biografía, foto y enlaces. El Collector ACC recibe resultados y datos de conducción.'),('Finalidades y bases jurídicas','El acceso ofrece el servicio solicitado (RGPD art. 6.1.b). Los resultados, la integridad deportiva y la prevención de abusos se basan en el interés legítimo (f). Los datos opcionales del perfil se basan en el consentimiento (a).'),('Publicación y niveles','Las carreras públicas pueden mostrar nombres, coches, tiempos, clasificaciones y estadísticas. Performance y SAFE son indicadores deportivos calculados automáticamente. Comunica errores para solicitar una revisión.'),('Proveedores','Supabase aloja datos y funciones, GitHub Pages las páginas públicas y Valve/Steam facilita la identificación. Pueden aplicarse sus políticas y posibles transferencias internacionales.'),('Conservación y seguridad','Las sesiones caducan a los 7 días. Los perfiles activos y resultados pueden conservarse en el archivo de la liga. Los tokens se cifran mediante hash en el servidor; las funciones privadas requieren sesión válida.'),('Tus derechos','Puedes solicitar acceso, rectificación, supresión, limitación, portabilidad u oponerte a ciertos tratamientos. Puedes retirar el consentimiento de los datos opcionales.'),('Reclamaciones','Puedes contactar con la autoridad belga de protección de datos o la autoridad competente de tu país.'),('Almacenamiento local','El idioma figura en la URL. El token se guarda en el almacenamiento de sesión; la guía inicial del perfil recuerda tu elección localmente. No usamos publicidad dirigida.'),('Cambios','Este aviso puede evolucionar con el sitio. Consulta la versión publicada para conocer la política vigente.')],
 },
}
