"""Visible editorial copy for the two leagues; same structure in every language."""
COPY={
'fr':{
 'home':'Accueil','league_acc':'La compétition GT3, vécue ensemble.','league_ace':'Une nouvelle façon de prendre la piste.','lead_acc':'Courses organisées, résultats officiels et chronos de la communauté ATXRACING sur ACC.','lead_ace':'La ligue ACE prend forme. Retrouvez ici ses courses, ses pilotes et ses classements dès leur ouverture.','explore':'Explorer la ligue','section':'Votre espace de course','formats':'Nos formats ACC','next':'Prochaines courses','schedule':'Calendrier','standings':'Classement officiel','fastest':'Le tour de référence','drivers':'Pilotes','browse':'Découvrir les pilotes','search':'Rechercher un pilote','search_hint':'Nom ou équipe','category':'Catégorie','track':'Circuit','published':'Données publiées','source':'Données du Collector ACC','no_events':'Aucune prochaine course publiée. Revenez bientôt consulter le calendrier.','no_data':'Aucune donnée officielle publiée pour cette rubrique.','unavailable':'Le service des résultats est momentanément indisponible.','ace_pending':'Les courses et résultats ACE apparaîtront après la mise en service du serveur et du collecteur dédiés.','back_acc':'Voir la ligue ACC','join':'S’inscrire','ranking_lead':'Suivez les pilotes et les équipes, catégorie par catégorie. Les points viennent des résultats officiels.','records_lead':'Les meilleurs tours valides, associés au circuit, au pilote et à la voiture utilisée.','profile_lead':'Une identité pilote pour les deux jeux. Retrouvez les performances ACC publiées et, à terme, celles d’ACE.','courses_lead':'Choisissez votre format et retrouvez les prochaines épreuves ATXRACING.','profile_public':'Profil public','discover':'Voir les courses','see_rank':'Voir le classement','see_records':'Explorer les chronos','see_profile':'Voir les pilotes','stage':'ESPACE PILOTE','formats_items':[
 ('World GT Sprint','Deux pilotes par équipage. Deux courses de 60 min et un changement de pilote obligatoire.'),
 ('World GT Endurance','Équipages de 1 à 6 pilotes. Des épreuves longues sur les grands circuits.'),
 ('Daily Race','Course de 60 min. Un arrêt obligatoire entre la 25e et la 35e minute.')],
},
'en':{
 'home':'Home','league_acc':'GT3 racing, together.','league_ace':'A new way to take to the track.','lead_acc':'Organised races, official results and community lap times on ACC.','lead_ace':'The ACE league is taking shape. Its races, drivers and standings will appear here when launched.','explore':'Explore the league','section':'Your racing hub','formats':'ACC race formats','next':'Upcoming races','schedule':'Calendar','standings':'Official standings','fastest':'Reference lap','drivers':'Drivers','browse':'Explore drivers','search':'Search for a driver','search_hint':'Name or team','category':'Category','track':'Track','published':'Published data','source':'ACC Collector data','no_events':'No upcoming race has been published. Check the calendar again soon.','no_data':'No official data has been published for this section.','unavailable':'The results service is temporarily unavailable.','ace_pending':'ACE races and results will appear after its dedicated server and collector go live.','back_acc':'View the ACC league','join':'Register','ranking_lead':'Follow drivers and teams by category. Points come from official results.','records_lead':'The fastest valid laps, with their track, driver and car.','profile_lead':'One driver identity for both games. See published ACC results and, later, ACE results.','courses_lead':'Choose a format and find upcoming ATXRACING events.','profile_public':'Public profile','discover':'View races','see_rank':'View standings','see_records':'Explore records','see_profile':'View drivers','stage':'DRIVER HUB','formats_items':[
 ('World GT Sprint','Two drivers per crew. Two 60-minute races and one mandatory driver change.'),
 ('World GT Endurance','Crews of 1 to 6 drivers. Long-distance events at major circuits.'),
 ('Daily Race','A 60-minute race. One mandatory stop between minutes 25 and 35.')],
},
'de':{
 'home':'Startseite','league_acc':'GT3-Rennsport, gemeinsam erlebt.','league_ace':'Ein neuer Weg auf die Rennstrecke.','lead_acc':'Organisierte Rennen, offizielle Ergebnisse und Rundenzeiten der ATXRACING-Community in ACC.','lead_ace':'Die ACE-Liga entsteht. Rennen, Fahrer und Wertungen erscheinen hier zum Start.','explore':'Liga entdecken','section':'Dein Rennbereich','formats':'ACC-Rennformate','next':'Nächste Rennen','schedule':'Kalender','standings':'Offizielle Wertung','fastest':'Referenzrunde','drivers':'Fahrer','browse':'Fahrer entdecken','search':'Fahrer suchen','search_hint':'Name oder Team','category':'Kategorie','track':'Strecke','published':'Veröffentlichte Daten','source':'Daten des ACC Collectors','no_events':'Derzeit ist kein kommendes Rennen veröffentlicht. Schau bald wieder vorbei.','no_data':'Für diesen Bereich liegen noch keine offiziellen Daten vor.','unavailable':'Der Ergebnisdienst ist vorübergehend nicht erreichbar.','ace_pending':'ACE-Rennen und Ergebnisse erscheinen nach dem Start des eigenen Servers und Collectors.','back_acc':'ACC-Liga ansehen','join':'Anmelden','ranking_lead':'Fahrer und Teams nach Kategorie verfolgen. Die Punkte stammen aus offiziellen Ergebnissen.','records_lead':'Die schnellsten gültigen Runden mit Strecke, Fahrer und Fahrzeug.','profile_lead':'Eine Fahreridentität für beide Spiele. Veröffentlichte ACC-Ergebnisse und später auch ACE-Ergebnisse.','courses_lead':'Wähle ein Format und entdecke die nächsten ATXRACING-Rennen.','profile_public':'Öffentliches Profil','discover':'Rennen ansehen','see_rank':'Wertung ansehen','see_records':'Bestzeiten ansehen','see_profile':'Fahrer ansehen','stage':'FAHRERBEREICH','formats_items':[
 ('World GT Sprint','Zwei Fahrer pro Team. Zwei Rennen à 60 Minuten mit vorgeschriebenem Fahrerwechsel.'),
 ('World GT Endurance','Teams mit 1 bis 6 Fahrern. Langstreckenrennen auf großen Rennstrecken.'),
 ('Daily Race','Rennen über 60 Minuten. Ein Pflichtstopp zwischen Minute 25 und 35.')],
},
'it':{
 'home':'Home','league_acc':'Le gare GT3, insieme.','league_ace':'Un nuovo modo di scendere in pista.','lead_acc':'Gare organizzate, risultati ufficiali e tempi sul giro della comunità ATXRACING in ACC.','lead_ace':'La lega ACE prende forma. Gare, piloti e classifiche appariranno qui all’avvio.','explore':'Scopri la lega','section':'Il tuo spazio corse','formats':'Formati di gara ACC','next':'Prossime gare','schedule':'Calendario','standings':'Classifica ufficiale','fastest':'Giro di riferimento','drivers':'Piloti','browse':'Scopri i piloti','search':'Cerca un pilota','search_hint':'Nome o squadra','category':'Categoria','track':'Circuito','published':'Dati pubblicati','source':'Dati dell’ACC Collector','no_events':'Non ci sono ancora gare future pubblicate. Controlla di nuovo il calendario.','no_data':'Non ci sono ancora dati ufficiali pubblicati per questa sezione.','unavailable':'Il servizio dei risultati è temporaneamente non disponibile.','ace_pending':'Gare e risultati ACE appariranno dopo l’avvio del server e del collector dedicati.','back_acc':'Vai alla lega ACC','join':'Iscriviti','ranking_lead':'Segui piloti e squadre per categoria. I punti provengono dai risultati ufficiali.','records_lead':'I giri validi più veloci, con circuito, pilota e auto utilizzata.','profile_lead':'Un’unica identità pilota per entrambi i giochi. Risultati ACC pubblicati e, in futuro, risultati ACE.','courses_lead':'Scegli un formato e scopri le prossime gare ATXRACING.','profile_public':'Profilo pubblico','discover':'Vedi le gare','see_rank':'Vedi la classifica','see_records':'Esplora i record','see_profile':'Vedi i piloti','stage':'SPAZIO PILOTI','formats_items':[
 ('World GT Sprint','Due piloti per equipaggio. Due gare di 60 minuti e un cambio pilota obbligatorio.'),
 ('World GT Endurance','Equipaggi da 1 a 6 piloti. Gare di durata sui grandi circuiti.'),
 ('Daily Race','Gara di 60 minuti. Una sosta obbligatoria tra il 25° e il 35° minuto.')],
},
'es':{
 'home':'Inicio','league_acc':'Competición GT3, juntos.','league_ace':'Una nueva forma de salir a pista.','lead_acc':'Carreras organizadas, resultados oficiales y tiempos por vuelta de la comunidad ATXRACING en ACC.','lead_ace':'La liga ACE está tomando forma. Sus carreras, pilotos y clasificaciones aparecerán aquí al comenzar.','explore':'Explorar la liga','section':'Tu espacio de competición','formats':'Formatos de carrera ACC','next':'Próximas carreras','schedule':'Calendario','standings':'Clasificación oficial','fastest':'Vuelta de referencia','drivers':'Pilotos','browse':'Descubrir pilotos','search':'Buscar piloto','search_hint':'Nombre o equipo','category':'Categoría','track':'Circuito','published':'Datos publicados','source':'Datos del ACC Collector','no_events':'Aún no hay carreras futuras publicadas. Vuelve a consultar el calendario.','no_data':'Todavía no hay datos oficiales publicados para esta sección.','unavailable':'El servicio de resultados no está disponible temporalmente.','ace_pending':'Las carreras y resultados ACE aparecerán cuando se activen su servidor y collector dedicados.','back_acc':'Ver la liga ACC','join':'Inscribirse','ranking_lead':'Sigue a pilotos y equipos por categoría. Los puntos proceden de resultados oficiales.','records_lead':'Las vueltas válidas más rápidas, con circuito, piloto y coche utilizado.','profile_lead':'Una sola identidad de piloto para ambos juegos. Resultados ACC publicados y, más adelante, de ACE.','courses_lead':'Elige un formato y descubre los próximos eventos ATXRACING.','profile_public':'Perfil público','discover':'Ver carreras','see_rank':'Ver clasificación','see_records':'Explorar tiempos','see_profile':'Ver pilotos','stage':'ESPACIO PILOTOS','formats_items':[
 ('World GT Sprint','Dos pilotos por equipo. Dos carreras de 60 minutos y un cambio de piloto obligatorio.'),
 ('World GT Endurance','Equipos de 1 a 6 pilotos. Pruebas de resistencia en grandes circuitos.'),
 ('Daily Race','Carrera de 60 minutos. Una parada obligatoria entre los minutos 25 y 35.')],
}}
