/* Same photographs as src/circuit-images.js; circuit selection supplies the ATX Series image. */
const photos={
  "barcelona": "assets/circuits/barcelona.webp",
  "brands_hatch": "assets/circuits/brands_hatch.webp",
  "circuit_of_the_americas": "assets/circuits/cota.webp",
  "cota": "assets/circuits/cota.webp",
  "donington_park": "assets/circuits/donington.webp",
  "donington": "assets/circuits/donington.webp",
  "hungaroring": "assets/circuits/hungaroring.webp",
  "imola": "assets/circuits/imola.webp",
  "indianapolis": "assets/circuits/indianapolis.webp",
  "kyalami": "assets/circuits/kyalami.webp",
  "laguna_seca": "https://www.roadracingworld.com/wp-content/uploads/rrw/b4dc59d3-8f9a-4885-893e-a46ecf458ece.jpg",
  "misano": "assets/circuits/misano.webp",
  "monza": "https://backoffice.gpt-worldwide.com/uploads/1599471039_3845352C-C193-4733-9A84-1138251A6D44.jpeg",
  "mount_panorama": "assets/circuits/mount_panorama.webp",
  "nurburgring": "assets/circuits/nurburgring.webp",
  "nurburgring_gp": "assets/circuits/nurburgring.webp",
  "nurburgring_24h": "assets/circuits/nurburgring_24h.webp",
  "oulton_park": "assets/circuits/oulton_park.webp",
  "paul_ricard": "assets/circuits/paul_ricard.webp",
  "red_bull_ring": "assets/circuits/red-bull-ring.jpg",
  "silverstone": "assets/circuits/silverstone.webp",
  "snetterton": "assets/circuits/snetterton.webp",
  "spa": "assets/circuits/spa.webp",
  "spa_francorchamps": "assets/circuits/spa.webp",
  "suzuka": "assets/circuits/suzuka.webp",
  "valencia": "assets/circuits/valencia.webp",
  "watkins_glen": "assets/circuits/watkins_glen.webp",
  "zandvoort": "assets/circuits/zandvoort.webp",
  "zolder": "assets/circuits/zolder.webp",
  "redbull_ring": "assets/circuits/red-bull-ring.jpg"
};
export function circuitPhoto(name,siteUrl){const key=String(name||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");const aliases={bathurst:"mount_panorama",nurburgringgp:"nurburgring",spa_francorchamps:"spa"};const image=photos[aliases[key]||key];return image?new URL(image,siteUrl.endsWith("/")?siteUrl:siteUrl+"/").href:"";}
