-- Run alongside the migrations in a BEGIN / ROLLBACK transaction. Synthetic accounts only.
DO $$
DECLARE a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); d uuid:=gen_random_uuid(); unverified uuid:=gen_random_uuid(); e uuid:=gen_random_uuid(); payload jsonb; response jsonb; before_count integer; wallet jsonb;
BEGIN
 INSERT INTO public.drivers(id,display_name,car_number) VALUES(a,'Synthetic A','37'),(b,'Synthetic B','38'),(c,'Synthetic C','39'),(d,'Synthetic D','40'),(unverified,'Synthetic unverified','41');
 INSERT INTO public.driver_identities(driver_id,steam_id64,last_login_at) VALUES(a,'70000000000000101',now()),(b,'70000000000000102',now()),(c,'70000000000000103',now()),(d,'70000000000000104',now()),(unverified,'70000000000000105',NULL);
 IF (SELECT count(*) FROM public.atx_coin_ledger WHERE driver_id=unverified)<>0 THEN RAISE EXCEPTION 'unverified account rewarded'; END IF;
 PERFORM public.atx_welcome_coins(a);PERFORM public.atx_welcome_coins(a);
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=a)<>10 THEN RAISE EXCEPTION 'welcome doubled'; END IF;
 INSERT INTO public.driver_profile_preferences(driver_id,nickname,profile_confirmed_at,acc_first_name,acc_last_name,acc_short_name) SELECT id,'Synthetic',now(),'Test','Driver','TST' FROM public.drivers WHERE id IN(a,b,c,d);
 PERFORM public.save_driver_profile(a,jsonb_build_object('display_name','Synthetic A','nickname','Synthetic','car_number','37','games_played','[]'::jsonb,'games_to_discover','[]'::jsonb,'favorite_circuits','[]'::jsonb,'acc_first_name','Test','acc_last_name','Driver','acc_short_name','TST','preferred_race_formats',jsonb_build_array('sprint_60','sprint_90','endurance')));
 IF (SELECT cardinality(preferred_race_formats) FROM public.driver_profile_preferences WHERE driver_id=a)<>3 THEN RAISE EXCEPTION 'multiple formats lost'; END IF;
 INSERT INTO public.events(id,slug,event_type,status,title_fr,title_en,circuit_name,circuit_key,starts_at,duration_minutes,max_drivers,is_public,competition_code,format_code,site_registration_enabled) VALUES(e,'paddock-synthetic-'||e,'daily_race','registration_open','Synthetic race','Synthetic race','Monza','monza',now()+interval '1 day',45,1,true,'ATXS','ATXS',true);
 payload:=jsonb_build_object('raceNumber',37,'carModelId',34,'teamName','');
 PERFORM public.atx_register_entry(a,e,'register',payload);
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=a)<>9 THEN RAISE EXCEPTION 'entry not charged once'; END IF;
 response:=public.atx_register_entry(b,e,'register',payload);IF response->>'waitlisted'<>'true' THEN RAISE EXCEPTION 'waitlist not created'; END IF;
 PERFORM public.atx_register_entry(c,e,'register',payload);
 -- Deterministic FIFO fixture: transactions share a timestamp, so set explicit queue order.
 UPDATE public.atx_waitlist SET created_at=now()-interval '2 minutes' WHERE driver_id=b AND event_id=e;
 UPDATE public.atx_waitlist SET created_at=now()-interval '1 minute' WHERE driver_id=c AND event_id=e;
 PERFORM public.atx_register_entry(a,e,'withdraw');PERFORM public.atx_register_entry(a,e,'withdraw');
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=a)<>10 THEN RAISE EXCEPTION 'withdrawal refund doubled'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.atx_waitlist WHERE driver_id=b AND event_id=e AND state='offered') THEN RAISE EXCEPTION 'FIFO reservation failed'; END IF;
 response:=public.atx_register_entry(c,e,'register',payload);IF response->>'waitlisted'<>'true' THEN RAISE EXCEPTION 'reserved place stolen'; END IF;
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=c)<>10 THEN RAISE EXCEPTION 'queue charged coins'; END IF;
 UPDATE public.atx_waitlist SET offered_until=now()-interval '1 minute' WHERE event_id=e AND driver_id=b;
 PERFORM public.atx_refresh_waitlist(e);
 IF NOT EXISTS(SELECT 1 FROM public.atx_waitlist WHERE driver_id=c AND event_id=e AND state='offered') THEN RAISE EXCEPTION 'expired offer blocked queue'; END IF;
 PERFORM public.atx_register_entry(c,e,'register',payload);
 UPDATE public.events SET status='registration_closed',site_registration_enabled=false WHERE id=e;
 PERFORM public.atx_register_entry(c,e,'withdraw');
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=c)<>10 THEN RAISE EXCEPTION 'closed registrations prevented withdrawal refund'; END IF;
 UPDATE public.events SET status='registration_open',site_registration_enabled=true WHERE id=e;
 INSERT INTO public.atx_coin_ledger(driver_id,amount,kind,operation_key) VALUES(d,-10,'adjustment','test:'||d);
 BEGIN PERFORM public.atx_register_entry(d,e,'register',payload); RAISE EXCEPTION 'insufficient coins accepted'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'insufficient_coins' THEN RAISE; END IF; END;
 IF EXISTS(SELECT 1 FROM public.atx_entry_members WHERE driver_id=d AND event_id=e) THEN RAISE EXCEPTION 'insufficient coins left registration'; END IF;
 PERFORM public.atx_register_entry(a,e,'register',payload);
 UPDATE public.events SET starts_at=now()-interval '1 hour',status='completed' WHERE id=e;
 INSERT INTO public.results(event_id,driver_id,status,finish_position,laps_completed,best_lap_ms,points) VALUES(e,a,'classified',1,10,100000,25),(e,b,'classified',2,10,105000,18),(e,unverified,'classified',3,10,110000,15);
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=a)<>9 THEN RAISE EXCEPTION 'provisional race paid rewards'; END IF;
 BEGIN PERFORM public.atx_review_results(b,e,'publication','{"state":"official","reasonFr":"Test","reasonEn":"Test"}'::jsonb); RAISE EXCEPTION 'non-staff review accepted'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'forbidden' THEN RAISE; END IF; END;
 INSERT INTO public.driver_roles(driver_id,role) VALUES(a,'admin');
 UPDATE public.events SET results_import_in_progress=true WHERE id=e;
 BEGIN PERFORM public.atx_review_results(a,e,'publication','{"state":"official","reasonFr":"Test","reasonEn":"Test"}'::jsonb); RAISE EXCEPTION 'incomplete import approved'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'results_import_in_progress' THEN RAISE; END IF; END;
 UPDATE public.events SET results_import_in_progress=false WHERE id=e;
 PERFORM public.atx_review_results(a,e,'publication','{"state":"official","reasonFr":"Test","reasonEn":"Test"}'::jsonb);
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=a)<>21 THEN RAISE EXCEPTION 'official rewards incorrect'; END IF;
 UPDATE public.driver_identities SET last_login_at=now() WHERE driver_id=unverified;
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=unverified)<>18 THEN RAISE EXCEPTION 'newly claimed historical rewards missing'; END IF;
 UPDATE public.driver_identities SET last_login_at=now() WHERE driver_id=unverified;
 IF (SELECT sum(amount) FROM public.atx_coin_ledger WHERE driver_id=unverified)<>18 THEN RAISE EXCEPTION 'repeated login paid historical rewards twice'; END IF;
 SELECT count(*) INTO before_count FROM public.atx_coin_ledger WHERE event_id=e;
 BEGIN PERFORM public.atx_review_results(a,e,'publication','{"state":"official","reasonFr":"Test","reasonEn":"Test"}'::jsonb); RAISE EXCEPTION 'repeat approval accepted'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'results_locked' THEN RAISE; END IF; END;
 BEGIN PERFORM public.atx_review_results(a,e,'correct',jsonb_build_object('driverId',a,'position',NULL,'status','dnf','points',0,'reasonFr','Test','reasonEn','Test')); RAISE EXCEPTION 'official correction accepted'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'results_locked' THEN RAISE; END IF; END;
 BEGIN DELETE FROM public.results WHERE event_id=e AND driver_id=b; RAISE EXCEPTION 'official import deletion accepted'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'results_locked' THEN RAISE; END IF; END;
 BEGIN UPDATE public.results SET points=0 WHERE event_id=e AND driver_id=a; RAISE EXCEPTION 'direct official correction accepted'; EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'results_locked' THEN RAISE; END IF; END;
 IF (SELECT count(*) FROM public.atx_coin_ledger WHERE event_id=e)<>before_count THEN RAISE EXCEPTION 'locked review changed coins'; END IF;
 wallet:=public.atx_driver_wallet(a);IF wallet->>'coins'<>'21' THEN RAISE EXCEPTION 'wallet balance inaccurate'; END IF;
END $$;
