/* Calendar, archives and race detail from the established public ACC event API. */
(() => {
 const root=document.querySelector('#results'),page=document.body.dataset.page,lang=document.documentElement.lang;
 if(!root||!['calendar','archives','event','course','worldgt','daily-race','ballade'].includes(page))return;
 const base=document.querySelector('meta[name="atx-base"]')?.content||'/atxracing/';
 const url='https://twjpjzalyvbsdpbzhqln.supabase.co/functions/v1/public-event';
 const dictionary={
 fr:{loading:'Chargement des courses…',error:'Les courses sont momentanément indisponibles.',empty:'Aucune course publiée pour cette sélection.',register:'S’inscrire sur SimGrid',results:'Résultats officiels',teams:'Équipes',driver:'Pilote',team:'Équipe',car:'Voiture',lap:'Meilleur tour',points:'Points',date:'Date',details:'Voir la course',archived:'Course terminée',upcoming:'Course programmée'},
 en:{loading:'Loading races…',error:'Races are temporarily unavailable.',empty:'No race published for this selection.',register:'Register on SimGrid',results:'Official results',teams:'Teams',driver:'Driver',team:'Team',car:'Car',lap:'Best lap',points:'Points',date:'Date',details:'View race',archived:'Completed race',upcoming:'Upcoming race'},
 de:{loading:'Rennen werden geladen…',error:'Rennen sind vorübergehend nicht verfügbar.',empty:'Keine Rennen für diese Auswahl veröffentlicht.',register:'Auf SimGrid anmelden',results:'Offizielle Ergebnisse',teams:'Teams',driver:'Fahrer',team:'Team',car:'Fahrzeug',lap:'Beste Runde',points:'Punkte',date:'Datum',details:'Rennen ansehen',archived:'Abgeschlossenes Rennen',upcoming:'Geplantes Rennen'},
 it:{loading:'Caricamento gare…',error:'Le gare sono temporaneamente indisponibili.',empty:'Nessuna gara pubblicata per questa selezione.',register:'Iscriviti su SimGrid',results:'Risultati ufficiali',teams:'Squadre',driver:'Pilota',team:'Squadra',car:'Auto',lap:'Miglior giro',points:'Punti',date:'Data',details:'Vedi gara',archived:'Gara conclusa',upcoming:'Gara in programma'},
 es:{loading:'Cargando carreras…',error:'Las carreras no están disponibles temporalmente.',empty:'No hay carreras publicadas para esta selección.',register:'Inscribirse en SimGrid',results:'Resultados oficiales',teams:'Equipos',driver:'Piloto',team:'Equipo',car:'Coche',lap:'Mejor vuelta',points:'Puntos',date:'Fecha',details:'Ver carrera',archived:'Carrera terminada',upcoming:'Próxima carrera'}
 }[lang];
 const el=(tag,cls,txt)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(txt!==undefined)x.textContent=String(txt);return x};
 const time=stamp=>stamp?new Intl.DateTimeFormat(lang,{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Brussels'}).format(new Date(stamp)):'—';
 const lap=ms=>ms>0?`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`:'—';
 const external=raw=>{try{const parsed=new URL(raw);return parsed.protocol==='https:'?parsed.href:null}catch{return null}};
 const type=e=>{const s=[e.server_name,e.title_fr,e.title_en,e.event_type].join(' ').toUpperCase();return /BALLADE\s+ATX/.test(s)?'BA':/\bWGT\b|WORLD\s?GT|ENDURANCE|SPRINT/.test(s)?'WGT':/\bDR\b|DAILY\s?RACE/.test(s)?'DR':null};
 const href=e=>base+lang+'/acc/course.html?slug='+encodeURIComponent(e.slug);
 const name=e=>e['title_'+lang]||e.title_en||e.title_fr||e.circuit_name||'ATXRACING';
 function tile(e){const a=el('a','event-tile');a.href=href(e);const poster=el('span','event-poster');const image=external(e.image_url);if(image){const img=el('img');img.src=image;img.alt='';img.loading='lazy';img.onerror=()=>img.remove();poster.append(img)}const body=el('span','event-copy');body.append(el('small','meta',(type(e)||'ACC')+' / '+time(e.starts_at)),el('strong','',name(e)),el('span','',e.circuit_name||''),el('small','',dictionary.details+' ↗'));a.append(poster,body);return a}
 function rows(headers,values){const wrap=el('div','ranking-table-wrap'),table=el('table','ranking-table'),head=el('thead'),tr=el('tr'),tbody=el('tbody');headers.forEach(h=>tr.append(el('th','',h)));head.append(tr);values.forEach(row=>{const tr=el('tr');row.forEach(value=>tr.append(el('td','',value??'—')));tbody.append(tr)});table.append(head,tbody);wrap.append(table);return wrap}
 const details={
 fr:{schedule:'Programme',settings:'Paramètres de course',cars:'Voitures',drivers:'Pilotes',maximum:'maximum',stops:'Arrêts obligatoires',tyres:'Pneus obligatoires',fuel:'Ravitaillement obligatoire',multiplier:'Temps accéléré',server:'Serveur',yes:'Oui',no:'Non',honours:'Distinctions',fast:'Fast Driver',gentleman:'Gentleman Driver',clean:'tours propres',penalties:'pénalité(s)',laps:'Tours',pending:'Le résultat officiel n’est pas encore publié.',teamPending:'Résultats ACC · équipages à valider',validation:'Résultats WorldGT · équipes en cours de validation',note:'Points WorldGT : le résultat de l’équipage attribue ses points à chaque pilote participant. Les points bruts de l’import ACC ne sont pas les points WorldGT.',overview:'Présentation',calendar:'Calendrier',race:'Course',standings:'Classement'},
 en:{schedule:'Schedule',settings:'Race settings',cars:'Cars',drivers:'Drivers',maximum:'maximum',stops:'Mandatory pit stops',tyres:'Mandatory tyres',fuel:'Mandatory refuelling',multiplier:'Time multiplier',server:'Server',yes:'Yes',no:'No',honours:'Awards',fast:'Fast Driver',gentleman:'Gentleman Driver',clean:'clean laps',penalties:'penalties',laps:'Laps',pending:'The official result has not been published yet.',teamPending:'ACC results · teams pending validation',validation:'WorldGT results · team validation pending',note:'WorldGT points: the team result awards points to every participating driver. Raw ACC import points are not WorldGT points.',overview:'Overview',calendar:'Calendar',race:'Race',standings:'Standings'},
 de:{schedule:'Zeitplan',settings:'Renndaten',cars:'Fahrzeuge',drivers:'Fahrer',maximum:'maximal',stops:'Pflichtstopps',tyres:'Pflichtreifenwechsel',fuel:'Pflichttanken',multiplier:'Zeitmultiplikator',server:'Server',yes:'Ja',no:'Nein',honours:'Auszeichnungen',fast:'Schnellster Fahrer',gentleman:'Fairer Fahrer',clean:'saubere Runden',penalties:'Strafen',laps:'Runden',pending:'Das offizielle Ergebnis wurde noch nicht veröffentlicht.',teamPending:'ACC-Ergebnisse · Teams noch zu bestätigen',validation:'WorldGT-Ergebnisse · Teamprüfung läuft',note:'WorldGT-Punkte: Das Teamergebnis bestimmt die Punkte aller beteiligten Fahrer. Die Rohpunkte des ACC-Imports gelten nicht als WorldGT-Punkte.',overview:'Übersicht',calendar:'Kalender',race:'Rennen',standings:'Wertung'},
 it:{schedule:'Programma',settings:'Impostazioni di gara',cars:'Auto',drivers:'Piloti',maximum:'massimo',stops:'Soste obbligatorie',tyres:'Cambio gomme obbligatorio',fuel:'Rifornimento obbligatorio',multiplier:'Moltiplicatore del tempo',server:'Server',yes:'Sì',no:'No',honours:'Riconoscimenti',fast:'Pilota più veloce',gentleman:'Pilota corretto',clean:'giri puliti',penalties:'penalità',laps:'Giri',pending:'Il risultato ufficiale non è ancora stato pubblicato.',teamPending:'Risultati ACC · squadre da confermare',validation:'Risultati WorldGT · verifica squadre in corso',note:'Punti WorldGT: il risultato della squadra assegna punti a ogni pilota partecipante. I punti grezzi importati da ACC non sono i punti WorldGT.',overview:'Panoramica',calendar:'Calendario',race:'Gara',standings:'Classifica'},
 es:{schedule:'Programa',settings:'Ajustes de carrera',cars:'Coches',drivers:'Pilotos',maximum:'máximo',stops:'Paradas obligatorias',tyres:'Cambio de neumáticos obligatorio',fuel:'Repostaje obligatorio',multiplier:'Multiplicador de tiempo',server:'Servidor',yes:'Sí',no:'No',honours:'Distinciones',fast:'Piloto más rápido',gentleman:'Piloto más limpio',clean:'vueltas limpias',penalties:'penalizaciones',laps:'Vueltas',pending:'El resultado oficial aún no se ha publicado.',teamPending:'Resultados ACC · equipos pendientes de validación',validation:'Resultados WorldGT · equipos en validación',note:'Puntos WorldGT: el resultado del equipo otorga puntos a cada piloto participante. Los puntos brutos importados de ACC no son los puntos WorldGT.',overview:'Presentación',calendar:'Calendario',race:'Carrera',standings:'Clasificación'}
 }[lang]||{};
 function eventDetail(payload){
  const e=payload.event||{},category=type(e)||'ACC',teamResults=category==='WGT'&&Array.isArray(payload.team_results)?payload.team_results:[],teamView=teamResults.length>0,results=Array.isArray(payload.results)?payload.results:[],display=teamView?teamResults:results;
  const main=el('article','official-race');const journey=el('nav','race-journey');journey.setAttribute('aria-label',details.race);
  const routes={WGT:'worldgt',DR:'daily-race',BA:'ballade'};const route=routes[category]||'courses';
  [[details.overview,route+'.html'],[details.calendar,'calendar.html?type='+category],[details.race,'#programme'],[dictionary.results,'#resultats'],[details.standings,'ranking.html?type='+category+'#points']].forEach(([label,target],i)=>{const a=el('a','',String(i+1).padStart(2,'0')+' · '+label);a.href=target[0]==='#'?target:base+lang+'/acc/'+target;journey.append(a)});
  main.append(journey,el('span','eyebrow',category+' / '+(e.circuit_name||'ACC')),el('h2','race-title',name(e)),el('p','race-meta',(e.circuit_name||'—')+' · '+time(e.starts_at)));
  const image=external(e.image_url);if(image){const photo=el('img','race-poster');photo.src=image;photo.alt='';photo.loading='lazy';main.append(photo)}
  const overview=el('section','race-overview');overview.id='programme';const schedule=el('div','race-schedule');schedule.append(el('h3','',details.schedule));
  (Array.isArray(e.event_schedule)?e.event_schedule:[]).forEach(item=>{const label=item['label'+lang[0].toUpperCase()+lang.slice(1)]||item['label_'+lang]||item.label_en||item.label_fr||item.key||'—';const block=el('div','race-spec');block.append(el('small','',label),el('strong','',String(item.start||'—').replace(':','h')+' – '+String(item.end||'—').replace(':','h')));schedule.append(block)});
  const settings=el('div','race-settings');settings.append(el('h3','',details.settings));const setting=(label,value)=>{const block=el('div','race-spec');block.append(el('small','',label),el('strong','',value));settings.append(block)};
  setting(details.cars,e.car_class||'GT3');setting(details.drivers,(e.max_drivers||'—')+' '+details.maximum);setting(details.stops,category==='BA'?'2 · 90 min':e.mandatory_pit_stop?details.yes:details.no);setting(details.tyres,e.mandatory_tyre_change?details.yes:details.no);setting(details.fuel,e.mandatory_refuelling?details.yes:details.no);setting(details.multiplier,'x'+(e.time_multiplier||1));if(e.server_name)setting(details.server,e.server_name);
  overview.append(schedule,settings);const registration=external(e.simgrid_url);if(registration){const link=el('a','action',dictionary.register+' ↗');link.href=registration;link.target='_blank';link.rel='noopener noreferrer';overview.append(link)}main.append(overview);
  const resultSection=el('section','race-results');resultSection.id='resultats';resultSection.append(el('h3','',category==='WGT'&&!teamView&&results.length?details.teamPending:category==='WGT'&&!payload.team_assignments_complete?details.validation:dictionary.results));
  const awards=Array.isArray(payload.honours)?payload.honours:[];if(awards.length){const honours=el('div','race-honours');[['fast_driver',details.fast],['gentleman_driver',details.gentleman]].forEach(([kind,label])=>{const award=awards.find(item=>item.award_type===kind);if(!award)return;const pilot=Array.isArray(award.driver)?award.driver[0]:award.driver;const card=el('article','race-honour');card.append(el('small','',label),el('strong','',pilot?.display_name||'ACC Driver'),el('span','',kind==='fast_driver'?lap(award.best_lap_ms):`${award.clean_laps||0} ${details.clean} · ${award.penalty_count||0} ${details.penalties}`));honours.append(card)});resultSection.append(honours)}
  if(category==='WGT'&&results.length)resultSection.append(el('p','race-scoring-note',details.note));
  if(display.length){const table=el('table','ranking-table');const thead=el('thead'),tr=el('tr'),tbody=el('tbody');['#',teamView?dictionary.team+' / '+details.drivers:dictionary.driver,dictionary.car,details.laps,dictionary.lap,dictionary.points].forEach(h=>tr.append(el('th','',h)));thead.append(tr);display.forEach(r=>{const driver=Array.isArray(r.driver)?r.driver[0]:r.driver;const name=teamView?String(r.team_name||'—')+' · '+(r.members||[]).join(' / '):driver?.display_name||'ACC Driver';const row=el('tr');[r.finish_position?'P'+r.finish_position:String(r.status||'—').toUpperCase(),name,r.car_model_name||'—',r.laps_completed??0,lap(r.best_lap_ms),category==='WGT'&&!teamView?'—':Number(r.points||0).toLocaleString(lang)].forEach(value=>row.append(el('td','',value)));tbody.append(row)});table.append(thead,tbody);const wrap=el('div','ranking-table-wrap');wrap.append(table);resultSection.append(wrap)}else resultSection.append(el('p','empty',details.pending));main.append(resultSection);root.replaceChildren(main);
 }
 async function load(){root.replaceChildren(el('p','loading',dictionary.loading));try{
  if(page==='event'||page==='course'){const slug=new URLSearchParams(location.search).get('slug')||new URLSearchParams(location.search).get('event');if(!slug||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)){root.replaceChildren(el('p','empty',dictionary.empty));return}const response=await fetch(url+'?slug='+encodeURIComponent(slug));if(!response.ok)throw Error(response.status);eventDetail(await response.json());return}
  const response=await fetch(url);if(!response.ok)throw Error(response.status);const data=await response.json();const items=page==='archives'?(data.archives||[]):(data.events||[]);let active=({worldgt:'WGT','daily-race':'DR',ballade:'BA'})[page]||new URLSearchParams(location.search).get('type')?.toUpperCase()||'ALL';const nav=document.querySelector('.event-categories');function render(){const filtered=items.filter(e=>active==='ALL'||type(e)===active);const grid=el('div','event-grid');filtered.forEach(e=>grid.append(tile(e)));root.replaceChildren(filtered.length?grid:el('p','empty',dictionary.empty));nav?.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===active)))}nav?.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.category;const query=new URLSearchParams(location.search);active==='ALL'?query.delete('type'):query.set('type',active);history.replaceState(null,'',location.pathname+(query.size?'?'+query:''));render()}));render()
 }catch{root.replaceChildren(el('p','empty',dictionary.error))}}
 load();
})();
