/* ACC rankings use the same public leaderboard and scoring as the established site. */
(() => {
  const root = document.querySelector('#ranking-app');
  if (!root) return;
  const content = document.querySelector('#ranking-content');
  const language = document.documentElement.lang;
  const copy = {
    fr:{loading:'Chargement du classement…',error:'Le classement est momentanément indisponible.',empty:'Aucune donnée publiée.',driver:'Pilote',points:'Points',races:'Courses',wins:'Victoires',podiums:'Podiums',pace:'Rythme et progression',next:'Prochain objectif',maximum:'Niveau maximal',first:'Premiers chronos requis',circuit:'Circuit',car:'Voiture',lap:'Meilleur tour',performance:'Performance',team:'Équipe',drivers:'Pilotes',average:'Indice moyen',select:'Choisir un pilote',reference:'Tour de référence',view:'Voir le profil',categories:'Catégories de course',all:'Toutes catégories',legends:['Rookie · 108%+','Challenger · 106–107,99%','Pro · 104–105,99%','Elite · 102–103,99%','Alien · 100–101,99%'],fp:'Essais libres',qualifying:'Qualifications',race:'Course',circuits:'Circuits',target:'Objectif',name:'Nom'},
    en:{loading:'Loading standings…',error:'The standings are temporarily unavailable.',empty:'No published results yet.',driver:'Driver',points:'Points',races:'Races',wins:'Wins',podiums:'Podiums',pace:'Pace and progression',next:'Next target',maximum:'Top level',first:'First lap times needed',circuit:'Circuit',car:'Car',lap:'Best lap',performance:'Performance',team:'Team',drivers:'Drivers',average:'Average pace',select:'Choose a driver',reference:'Reference lap',view:'View profile',categories:'Race categories',all:'All categories',legends:['Rookie · 108%+','Challenger · 106–107.99%','Pro · 104–105.99%','Elite · 102–103.99%','Alien · 100–101.99%'],fp:'Practice',qualifying:'Qualifying',race:'Race',circuits:'Circuits',target:'Target',name:'Name'},
    de:{loading:'Wertung wird geladen…',error:'Die Wertung ist vorübergehend nicht verfügbar.',empty:'Noch keine veröffentlichten Ergebnisse.',driver:'Fahrer',points:'Punkte',races:'Rennen',wins:'Siege',podiums:'Podien',pace:'Tempo und Entwicklung',next:'Nächstes Ziel',maximum:'Höchste Stufe',first:'Erste Rundenzeiten nötig',circuit:'Strecke',car:'Fahrzeug',lap:'Beste Runde',performance:'Leistung',team:'Team',drivers:'Fahrer',average:'Durchschnittstempo',select:'Fahrer wählen',reference:'Referenzrunde',view:'Profil ansehen',categories:'Rennkategorien',all:'Alle Kategorien',legends:['Rookie · ab 108 %','Challenger · 106–107,99 %','Pro · 104–105,99 %','Elite · 102–103,99 %','Alien · 100–101,99 %'],fp:'Training',qualifying:'Qualifikation',race:'Rennen',circuits:'Strecken',target:'Ziel',name:'Name'},
    it:{loading:'Caricamento classifica…',error:'La classifica è temporaneamente non disponibile.',empty:'Nessun risultato pubblicato.',driver:'Pilota',points:'Punti',races:'Gare',wins:'Vittorie',podiums:'Podi',pace:'Ritmo e progressione',next:'Prossimo obiettivo',maximum:'Livello massimo',first:'Servono i primi tempi',circuit:'Circuito',car:'Auto',lap:'Miglior giro',performance:'Prestazione',team:'Squadra',drivers:'Piloti',average:'Ritmo medio',select:'Scegli un pilota',reference:'Giro di riferimento',view:'Vedi profilo',categories:'Categorie di gara',all:'Tutte le categorie',legends:['Rookie · 108%+','Challenger · 106–107,99%','Pro · 104–105,99%','Elite · 102–103,99%','Alien · 100–101,99%'],fp:'Prove libere',qualifying:'Qualifiche',race:'Gara',circuits:'Circuiti',target:'Obiettivo',name:'Nome'},
    es:{loading:'Cargando clasificación…',error:'La clasificación no está disponible temporalmente.',empty:'Aún no hay resultados publicados.',driver:'Piloto',points:'Puntos',races:'Carreras',wins:'Victorias',podiums:'Podios',pace:'Ritmo y progreso',next:'Próximo objetivo',maximum:'Nivel máximo',first:'Faltan tiempos de vuelta',circuit:'Circuito',car:'Coche',lap:'Mejor vuelta',performance:'Rendimiento',team:'Equipo',drivers:'Pilotos',average:'Ritmo medio',select:'Elegir piloto',reference:'Vuelta de referencia',view:'Ver perfil',categories:'Categorías de carrera',all:'Todas las categorías',legends:['Rookie · 108%+','Challenger · 106–107,99%','Pro · 104–105,99%','Elite · 102–103,99%','Alien · 100–101,99%'],fp:'Entrenamientos',qualifying:'Clasificación',race:'Carrera',circuits:'Circuitos',target:'Objetivo',name:'Nombre'}
  }[language] || {};
  const endpoint = 'https://twjpjzalyvbsdpbzhqln.supabase.co/functions/v1/public-leaderboard';
  const base = document.querySelector('meta[name="atx-base"]')?.content || '/atxracing/';
  const validCategories = ['WGT','DR','ATXS'];
  const query = new URLSearchParams(location.search);
  let category = validCategories.includes(query.get('type')?.toUpperCase()) ? query.get('type').toUpperCase() : 'DR';
  let view = location.hash.slice(1)==='team' ? 'team' : 'points';
  const cache = new Map();
  let renderSequence = 0;
  const el = (tag, className, value) => {const x=document.createElement(tag);if(className)x.className=className;if(value!==undefined)x.textContent=String(value);return x};
  const append = (parent, ...children) => {parent.append(...children);return parent};
  const format = n => Number(n||0).toLocaleString(language,{maximumFractionDigits:1});
  const percent = n => Number(n).toLocaleString(language,{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
  const lap = ms => ms>0 ? `${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}` : '—';
  const tier = t => ['rookie','challenger','pro','elite','alien'].includes(t) ? t : 'unranked';
  const progress = (t,n) => !Number.isFinite(n)||t==='unranked' ? 0 : t==='alien'?100:Math.max(0,Math.min(100,(({elite:104,pro:106,challenger:108,rookie:112})[t]-n)/(t==='rookie'?4:2)*100));
  const target = t => ({rookie:'Challenger · '+percent(107.99),challenger:'Pro · '+percent(105.99),pro:'Elite · '+percent(103.99),elite:'Alien · '+percent(101.99),alien:copy.maximum})[t]||copy.first;
  function avatar(driver){const wrap=el('span','ranking-avatar');const url=String(driver.avatar_url||'');if(/^https:\/\//.test(url)){const image=el('img');image.src=url;image.alt='';image.loading='lazy';image.referrerPolicy='no-referrer';image.onerror=()=>wrap.replaceChildren(el('span','',String(driver.display_name||'AT').slice(0,2).toUpperCase()));wrap.append(image)}else wrap.textContent=String(driver.display_name||'AT').slice(0,2).toUpperCase();return wrap}
  function driverLink(driver){const name=el(driver.profile_id?'a':'strong','ranking-name',driver.display_name||'—');if(driver.profile_id)name.href=base+language+'/acc/profile.html?driver='+encodeURIComponent(driver.profile_id);return append(el('span','ranking-driver'),avatar(driver),name)}
  function meter(value,kind){const rail=el('span','ranking-meter '+kind);rail.setAttribute('role','progressbar');rail.setAttribute('aria-valuemin','0');rail.setAttribute('aria-valuemax','100');rail.setAttribute('aria-valuenow',String(Math.round(value)));const fill=el('i');fill.style.width=Math.max(0,Math.min(100,value))+'%';rail.append(fill);return rail}
  const empty = ()=>el('p','empty',copy.empty);
  async function fetchRanking(scope){if(cache.has(scope))return cache.get(scope);const request=fetch(endpoint+'?category='+encodeURIComponent(scope),{signal:AbortSignal.timeout(12000)}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});cache.set(scope,request);request.catch(()=>cache.delete(scope));return request}
  function categories(){const nav=el('nav','ranking-categories');nav.setAttribute('aria-label',copy.categories);[['WGT','WorldGT'],['DR','Daily Race'],['ATXS','ATX Series']].forEach(([code,label])=>{const b=el('button','ranking-category');b.type='button';b.dataset.category=code;b.append(el('strong','',label),el('small','',code));b.addEventListener('click',()=>{category=code;const q=new URLSearchParams(location.search);q.set('type',code);q.delete('team');history.replaceState(null,'',location.pathname+'?'+q+'#'+view);render()});nav.append(b)});return nav}
  function legend(){const row=el('div','ranking-legend');['rookie','challenger','pro','elite','alien'].forEach((name,i)=>{const b=el('span','standing-tier',copy.legends[i]);b.dataset.level=name;row.append(b)});return row}
  function paceCell(d){const t=tier(d.performance_class),box=el('div','pace-cell'),head=el('div','pace-head'),badge=el('b','tier-badge tier-'+t,t.toUpperCase()),score=d.performance_score==null?NaN:Number(d.performance_score),trend=Number(d.progression);head.append(badge,el('strong','',Number.isFinite(score)&&d.performance_score!=null?percent(score):'—'));if(d.progression!=null&&Math.abs(trend)>.005){const movement=el('span','trend '+(trend>0?'gain':'loss'),(trend>0?'↑ ':'↓ ')+percent(Math.abs(trend)));head.append(movement)}box.append(head,meter(progress(t,score),'pace'),el('small','pace-target',copy.next+' : '+target(t)));return box}
  function safeCell(d){const n=Number(d.safety_score),box=el('div','safe-cell');if(d.safety_class)box.append(el('b','safe-badge safe-'+d.safety_class,d.safety_class.toUpperCase()));if(d.safety_score!=null&&Number.isFinite(n)){box.append(meter(n,'safe'),el('small','',Math.round(n)+' / 100'))}else if(!d.safety_class)box.textContent='—';return box}
  function standing(d,isTeam=false){const row=el('li','standing-row');row.dataset.level=isTeam||d.profile_id?tier(d.performance_class):'unranked';row.append(el('span','standing-position',String(d.rank||'—').padStart(2,'0')));const identity=el('div','standing-identity');if(isTeam){const a=el('a','ranking-name',d.team_name);a.href=base+language+'/acc/ranking.html?type='+category+'&team='+encodeURIComponent(d.team_name)+'#team';identity.append(a,el('small','',format(d.drivers)+' '+copy.drivers))}else identity.append(driverLink(d),el('small','',d.team_name||''));row.append(identity);const stats=el('dl','standing-stats');[[copy.points,d.points],[copy.races,d.races],[copy.wins,d.wins],[copy.podiums,d.podiums]].forEach(([label,value])=>{const group=el('div');group.append(el('dt','',label),el('dd','',format(value)));stats.append(group)});row.append(stats);const pace=el('div','standing-pace');pace.append(el('small','meta',isTeam?copy.average:copy.pace),paceCell(isTeam||d.profile_id?d:{...d,performance_class:'unranked',performance_score:null,progression:null}));row.append(pace);if(!isTeam){const safe=el('div','standing-safe');safe.append(el('small','meta','SAFE'),safeCell(d.profile_id?d:{safety_class:null,safety_score:null}));row.append(safe)}return row}
  function standings(items,isTeam=false){const list=el('ol','standing-list');items.forEach(d=>list.append(standing(d,isTeam)));return items.length?list:empty()}
  function points(data){const section=el('section','rank-panel');section.append(categories(),legend(),standings(data.drivers||[]));return section}
  function team(data){const section=el('section','rank-panel'),teams=data.teams||[],name=new URLSearchParams(location.search).get('team');section.append(categories(),legend());if(name){const selected=teams.find(t=>t.team_name===name),back=el('a','pill',language==='fr'?'← Toutes les équipes':'← All teams');back.href=base+language+'/acc/ranking.html?type='+category+'#team';section.append(back,el('h2','',name));if(selected){section.append(standings([selected],true),el('h3','',language==='fr'?'Composition des pilotes':'Driver lineup'));const members=selected.members||[];section.append(standings(members.map((d,i)=>({...d,rank:i+1}))))}else section.append(empty())}else section.append(standings(teams.map(d=>({...d,performance_class:d.performance_class||classFromScore(d.performance_score)})),true));return section}
  function classFromScore(score){return score==null?'unranked':score<102?'alien':score<104?'elite':score<106?'pro':score<108?'challenger':'rookie'}
  async function render(){const sequence=++renderSequence;root.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.setAttribute('aria-current',active?'page':'false')});content.replaceChildren(el('p','loading',copy.loading));try{const data=await fetchRanking(category);if(sequence!==renderSequence)return;content.replaceChildren(({points,team})[view](data));content.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)))}catch(error){if(sequence===renderSequence)content.replaceChildren(el('p','empty',copy.error))}}
  function updateTitle(){const heading=document.querySelector('[data-ranking-title]');if(heading)heading.textContent=language==='fr'?(view==='team'?'Classement par équipe':'Classement par pilote'):(view==='team'?'Team standings':'Driver standings')}
  root.querySelectorAll('[data-view]').forEach(b=>{b.addEventListener('click',()=>{view=b.dataset.view;history.replaceState(null,'',location.pathname+location.search+'#'+view);render()})});
  window.addEventListener('hashchange',()=>{view=location.hash.slice(1)==='team'?'team':'points';render()});
  render();
  updateTitle();
  root.addEventListener('click',updateTitle);
  window.addEventListener('hashchange',updateTitle);
})();
